Repository SAP/jenkins-library, pull requests merged in 2019-03, with the labels that each got.

#468 Remove compatibility for neoDeploy
  src/com/sap/piper/tools/neo/NeoCommandHelper.groovy
  test/groovy/FioriOnCloudPlatformPipelineTest.groovy
  test/groovy/NeoDeployTest.groovy
  test/groovy/com/sap/piper/tools/neo/NeoCommandHelperTest.groovy
  vars/neoDeploy.groovy
Labels: discussion

#543 uiVeri5ExecuteTests: add testServerUrl
  vars/uiVeri5ExecuteTests.groovy
Labels: REVIEW

#563 handlePipelineStepErrors: add error data to influx measurement
  vars/handlePipelineStepErrors.groovy
Labels: REVIEW

#523 Reduce redundancies in md files
  documentation/bin/createDocu.groovy
  documentation/docs/steps/checkChangeInDevelopment.md
  documentation/docs/steps/dockerExecute.md
  documentation/docs/steps/dockerExecuteOnKubernetes.md
  documentation/docs/steps/karmaExecuteTests.md
  documentation/docs/steps/npmExecute.md
  documentation/docs/steps/uiVeri5ExecuteTests.md
Labels: documentation

#500 Fix generation of stage scope documentation
  documentation/bin/createDocu.groovy
  test/groovy/CheckChangeInDevelopmentTest.groovy
Labels: documentation

#570 snykExecute: add missing documentation
  documentation/docs/steps/snykExecute.md
  documentation/mkdocs.yml
  vars/snykExecute.groovy
Labels: REVIEW, documentation

#569 seleniumExecuteTests: fix type
  vars/seleniumExecuteTests.groovy
Labels: REVIEW

#568 seleniumExecuteTests & uiVeri5ExecuteTests: improve documentation
  documentation/docs/steps/seleniumExecuteTests.md
  vars/seleniumExecuteTests.groovy
  vars/uiVeri5ExecuteTests.groovy
Labels: REVIEW, documentation

#574 Fix sanity checks for warPropertiesFile deploy mode.
  test/groovy/NeoDeployTest.groovy
  vars/neoDeploy.groovy
Labels: REVIEW

#562 bump version
  pom.xml
Labels: MERGE

#585 influx: report build link to influx measurements
  vars/commonPipelineEnvironment.groovy
  vars/setupCommonPipelineEnvironment.groovy
Labels: REVIEW, enhancement

#584 mailSendNotification: generate documentation
  documentation/docs/steps/mailSendNotification.md
  vars/mailSendNotification.groovy
Labels: MERGE, REVIEW, documentation

#592 slackSendNotification: generate documentation
  documentation/docs/steps/slackSendNotification.md
  vars/slackSendNotification.groovy
Labels: MERGE, REVIEW, documentation

#591 newmanExecute: generate documentation
  documentation/docs/steps/newmanExecute.md
  vars/newmanExecute.groovy
Labels: MERGE, REVIEW, documentation

#516 web analytics: add reporting for dockerExecute and dockerExecuteOnKubernetes
  vars/dockerExecute.groovy
  vars/dockerExecuteOnKubernetes.groovy
Labels: MERGE, REVIEW

#594 [docu] remove old reference pipelines
  README.md
Labels: REVIEW, documentation

#593 Prerequiste transportRequestCreate: SOLMAN ST720 SP08 or higher
  documentation/docs/steps/transportRequestCreate.md
Labels: documentation

#587 web analytics: use httpRequest step
  src/com/sap/piper/analytics/Telemetry.groovy
  test/groovy/com/sap/piper/analytics/TelemetryTest.groovy
Labels: MERGE, REVIEW

#595 Format neo deploy test
  test/groovy/NeoDeployTest.groovy
Labels: MERGE

#589 Remove step toolValidate
  documentation/docs/steps/toolValidate.md
  documentation/mkdocs.yml
  src/com/sap/piper/EnvironmentUtils.groovy
  src/com/sap/piper/FileUtils.groovy
  src/com/sap/piper/Version.groovy
  src/com/sap/piper/VersionUtils.groovy
  src/com/sap/piper/tools/JavaArchiveDescriptor.groovy
  src/com/sap/piper/tools/ToolDescriptor.groovy
  test/groovy/CommonStepsTest.groovy
  test/groovy/FioriOnCloudPlatformPipelineTest.groovy
  test/groovy/MtaBuildTest.groovy
  test/groovy/NeoDeployTest.groovy
  test/groovy/ToolValidateTest.groovy
  test/groovy/com/sap/piper/EnvironmentUtilsTest.groovy
  test/groovy/com/sap/piper/FileUtilsTest.groovy
  test/groovy/com/sap/piper/VersionTest.groovy
  test/groovy/com/sap/piper/VersionUtilsTest.groovy
  test/groovy/com/sap/piper/tools/JavaArchiveDescriptorTest.groovy
  test/groovy/com/sap/piper/tools/ToolDescriptorTest.groovy
  vars/mtaBuild.groovy
  vars/toolValidate.groovy
Labels: MERGE
