Repository SAP/jenkins-library, pull requests merged in 2019-08, with the labels that each got.

#848 more precise param handover (gitUrl) in piperPipelineStageInit
  test/groovy/templates/PiperPipelineStageInitTest.groovy
  vars/piperPipelineStageInit.groovy
Labels: REVIEW

#861 Link the SAP Cloud SDK
  documentation/docs/scenarios/CAP_Scenario.md
Labels: discussion

#863 Remove template docu page for piperPipelinStagePost
  documentation/docs/steps/piperPipelineStagePost.md
Labels: documentation
