Repository SAP/jenkins-library, pull requests merged in 2019-11, with the labels that each got.

#938 Add GO logging with logrus
  cmd/karmaExecuteTests.go
  cmd/karmaExecuteTests_generated.go
  cmd/karmaExecuteTests_test.go
  cmd/version_generated.go
  go.mod
  go.sum
  pkg/generator/step-metadata.go
  pkg/generator/testdata/TestProcessMetaFiles/step_code_generated.golden
  pkg/log/log.go
Labels: go-piper

#950 Apply proper go fmt formatting
  cmd/piper_test.go
  cmd/version_test.go
Labels: go-piper

#951 Fix: getting config should also work in case there is no project config
  cmd/getConfig.go
  pkg/config/config.go
Labels: go-piper

#928 Add PiperGoUtils for downloading piper binary
  .gitignore
  go.sum
  src/com/sap/piper/JenkinsUtils.groovy
  src/com/sap/piper/PiperGoUtils.groovy
  test/groovy/com/sap/piper/JenkinsUtilsTest.groovy
  test/groovy/com/sap/piper/PiperGoUtilsTest.groovy
Labels: go-piper

#945 Add capability for hierarchical defaults in golang
  .gitignore
  cmd/getConfig.go
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/stepmeta.go
  pkg/config/stepmeta_test.go
Labels: go-piper

#947 Add githubPublishRelease step
  cmd/githubPublishRelease.go
  cmd/githubPublishRelease_generated.go
  cmd/githubPublishRelease_generated_test.go
  cmd/githubPublishRelease_test.go
  cmd/karmaExecuteTests_generated.go
  cmd/piper.go
  cmd/testdata/TestRunGithubPublishRelease/Success_-_update_asset_test.txt
  cmd/testdata/TestUploadReleaseAsset/Success_-_existing_asset_test.txt
  cmd/testdata/TestUploadReleaseAsset/Success_-_no_asset_test.txt
  cmd/version_generated.go
  go.mod
  go.sum
  pkg/generator/step-metadata.go
  pkg/generator/step-metadata_test.go
  pkg/generator/testdata/TestProcessMetaFiles/step_code_generated.golden
  pkg/github/github.go
  resources/metadata/githubrelease.yaml
Labels: go-piper

#793 Add step spinnakerTriggerPipeline
  resources/default_pipeline_environment.yml
  test/groovy/SpinnakerTriggerPipelineTest.groovy
  vars/spinnakerTriggerPipeline.groovy
Labels: REVIEW

#944 Map with single parameter
  vars/cfManifestSubstituteVariables.groovy
Labels: bug :bug:

#954 Helper for fileExists
  cmd/getConfig.go
  pkg/piperutils/FileUtils.go
Labels: go-piper

#940 Let the mocks fail if error is provided from a test
  cmd/karmaExecuteTests_test.go
  cmd/piper_test.go
Labels: go-piper

#958 Export step generator
  pkg/generator/step-metadata.go
  pkg/generator/step-metadata_test.go
  pkg/generator/testdata/TestProcessMetaFiles/step_code_generated.golden
Labels: go-piper

#964 Fix bug in step generator
  pkg/generator/helper/helper.go
Labels: go-piper

#959 Pr/read project config only if it exists
  cmd/piper.go
  cmd/piper_test.go
Labels: go-piper

#968 assign library field in logger with respect of containing repository
  Dockerfile
  pkg/log/log.go
Labels: go-piper

#969 fix version command
  Dockerfile
Labels: go-piper

#888 Back commonPipelineEnvironment step by shared class
  src/com/sap/piper/CommonPipelineEnvironment.groovy
  test/groovy/util/JenkinsResetDefaultCacheRule.groovy
  vars/commonPipelineEnvironment.groovy
Labels: NoScriptReference

#822 config loader without script reference
  src/com/sap/piper/CommonPipelineEnvironment.groovy
  src/com/sap/piper/ConfigurationHelper.groovy
  src/com/sap/piper/ConfigurationLoader.groovy
  test/groovy/ChecksPublishResultsTest.groovy
  test/groovy/com/sap/piper/ConfigurationHelperTest.groovy
  test/groovy/com/sap/piper/ConfigurationLoaderTest.groovy
Labels: NoScriptReference, REVIEW

#856 Doc for mtaJarLocation and dockerImage config
  vars/dockerExecute.groovy
  vars/mtaBuild.groovy
Labels: documentation, work in progress 🚧

#858 Clarify content of fioriOnCloudPlatformPipeline
  documentation/docs/scenarios/ui5-sap-cp/Readme.md
Labels: documentation

#948 Add stdout/stderr to the interfaces (shellRunner, execRunner)
  cmd/interfaces.go
  cmd/karmaExecuteTests.go
  cmd/piper_test.go
  pkg/command/command.go
  pkg/command/command_test.go
Labels: go-piper

#985 Add Docker options to the step meta data
  pkg/config/stepmeta.go
  pkg/config/stepmeta_test.go
Labels: go-piper

#995 Consider custom defaults in config.yml
  cmd/getConfig.go
  cmd/githubPublishRelease_generated.go
  cmd/karmaExecuteTests_generated.go
  cmd/piper.go
  cmd/piper_test.go
  cmd/version_generated.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/generator/helper/helper.go
  pkg/generator/helper/testdata/TestProcessMetaFiles/step_code_generated.golden
Labels: go-piper

#990 Use piper binary for githubPublishRelease
  cmd/githubPublishRelease.go
  cmd/githubPublishRelease_generated.go
  cmd/githubPublishRelease_test.go
  cmd/karmaExecuteTests_generated.go
  go.mod
  pkg/generator/helper/helper.go
  pkg/generator/helper/testdata/TestProcessMetaFiles/step_code_generated.golden
  resources/metadata/githubrelease.yaml
  src/com/sap/piper/PiperGoUtils.groovy
  test/groovy/CommonStepsTest.groovy
  test/groovy/GithubPublishReleaseTest.groovy
  test/groovy/com/sap/piper/PiperGoUtilsTest.groovy
  vars/githubPublishRelease.groovy
Labels: go-piper

#973 Added docu generation to step generator
  pkg/generator/helper/docuHelper.go
  pkg/generator/helper/docuHelper_test.go
  pkg/generator/helper/goUtils.go
  pkg/generator/helper/helper.go
  pkg/generator/helper/helper_test.go
  pkg/generator/helper/piper-context-defaults.yaml
  pkg/generator/step-metadata.go
Labels: go-piper

#998 Remove redundancy: no duplicate stepName
  cmd/getConfig.go
  cmd/getConfig_test.go
Labels: go-piper

#1000 Fix issues in config resolution
  pkg/config/config.go
  pkg/config/config_test.go
  resources/metadata/githubrelease.yaml
Labels: go-piper

#1004 Fix parameters for githubPublishrelease
  cmd/githubPublishRelease_generated.go
  go.mod
  go.sum
  resources/metadata/githubrelease.yaml
Labels: go-piper

#1010 Docu generation for GoLang Steps
  .travis.yml
Labels: go-piper

#1014 fixed docu generation layout
  pkg/generator/helper/docuHelper.go
  pkg/generator/helper/docuHelper_test.go
Labels: go-piper

#1015 docs(sonar): correct sonar docs
  vars/sonarExecuteScan.groovy
Labels: documentation

#1006 chore(go): add pre-commit hook
  .hooks/README.md
  .hooks/pre-commit
Labels: go-piper
