Repository SAP/jenkins-library, pull requests merged in 2019-01, with the labels that each got.

#388 New Scenario Step: SAP UI5 on SAP Cloud Platform
  .codeclimate.yml
  documentation/docs/scenarios/ui5-sap-cp/Readme.md
  documentation/docs/scenarios/ui5-sap-cp/files/.npmrc
  documentation/docs/scenarios/ui5-sap-cp/files/Gruntfile.js
  documentation/docs/scenarios/ui5-sap-cp/files/mta.yaml
  documentation/docs/scenarios/ui5-sap-cp/files/package.json
  documentation/docs/scenarios/ui5-sap-cp/images/pipeline.jpg
  documentation/mkdocs.yml
  test/groovy/FioriOnCloudPlatformPipelineTest.groovy
  vars/fioriOnCloudPlatformPipeline.groovy
Labels: discussion, documentation, work in progress

#410 Documentation: Hybrid Applications with Jenkins and SAP Solution Manager
  documentation/docs/scenarios/changeManagement.md
  documentation/mkdocs.yml
Labels: documentation

#422 generate docu during build
  .travis.yml
  createDocu.sh
  documentation/bin/createDocu.groovy
  documentation/bin/createDocu.sh
  documentation/docs/steps/checkChangeInDevelopment.md
  documentation/mkdocs.yml
  src/com/sap/piper/GenerateDocumentation.java
  vars/checkChangeInDevelopment.groovy
Labels: documentation

#435 Doc: Introduce google group as communication channel
  README.md
Labels: documentation

#440 Improve neo deploy
  documentation/docs/steps/neoDeploy.md
  resources/default_pipeline_environment.yml
  src/com/sap/piper/BashUtils.groovy
  src/com/sap/piper/ConfigurationHelper.groovy
  src/com/sap/piper/StepAssertions.groovy
  src/com/sap/piper/tools/neo/DeployMode.groovy
  src/com/sap/piper/tools/neo/NeoCommandHelper.groovy
  src/com/sap/piper/tools/neo/WarAction.groovy
  test/groovy/FioriOnCloudPlatformPipelineTest.groovy
  test/groovy/NeoDeployTest.groovy
  test/groovy/com/sap/piper/BashUtilsTest.groovy
  test/groovy/com/sap/piper/tools/neo/NeoCommandHelperTest.groovy
  test/groovy/util/CommandLineMatcher.groovy
  test/groovy/util/JenkinsCredentialsRule.groovy
  test/groovy/util/JenkinsFileExistsRule.groovy
  test/groovy/util/JenkinsLockRule.groovy
  test/groovy/util/JenkinsPropertiesRule.groovy
  test/groovy/util/JenkinsShellCallRule.groovy
  test/groovy/util/JenkinsWithEnvRule.groovy
  vars/neoDeploy.groovy
Labels: REVIEW

#460 Stop old instance only if it exists in cf space
  test/groovy/CloudFoundryDeployTest.groovy
  vars/cloudFoundryDeploy.groovy
Labels: REVIEW

#439 extend Analytics
  src/com/sap/piper/Utils.groovy
  src/com/sap/piper/analytics/Telemetry.groovy
  test/groovy/com/sap/piper/UtilsTest.groovy
  test/groovy/com/sap/piper/analytics/TelemetryTest.groovy
  vars/piperStageWrapper.groovy
Labels: REVIEW
