Repository SAP/jenkins-library, pull requests merged in 2019-05, with the labels that each got.

#693 Enable configuration of npm registry for mtaBuild
  test/groovy/MtaBuildTest.groovy
  vars/mtaBuild.groovy
Labels: REVIEW

#682 fix wrong message
  src/com/sap/piper/ConfigurationHelper.groovy
  test/groovy/NeoDeployTest.groovy
  test/groovy/com/sap/piper/ConfigurationHelperTest.groovy
Labels: REVIEW, bug

#699 detectExecuteScan - add doc to docs structure
  documentation/mkdocs.yml
Labels: documentation

#183 add step for Sonar scan
  documentation/docs/steps/sonarExecuteScan.md
  resources/default_pipeline_environment.yml
  test/groovy/SonarExecuteTest.groovy
  test/groovy/util/JenkinsSetupRule.groovy
  vars/sonarExecuteScan.groovy
Labels: REVIEW

#704 add Sonar docs link
  documentation/mkdocs.yml
Labels: documentation

#697 Fix exception list for step neoDeploy
  documentation/docs/steps/neoDeploy.md
Labels: bug, documentation

#698 [fix] do not return a wrong config value if only a part of the path c…
  documentation/bin/createDocu.groovy
Labels: bug, documentation

#701 Provide a deep config copy from ConfigHelper.use()
  src/com/sap/piper/ConfigurationHelper.groovy
  src/com/sap/piper/MapUtils.groovy
  test/groovy/com/sap/piper/MapUtilsTest.groovy
Labels: bug

#710 fix: null is rendered when no default value is available instead of t…
  documentation/bin/createDocu.groovy
Labels: documentation

#659 Switch to named parameters when invoking docu generation
  documentation/bin/createDocu.groovy
Labels: REVIEW

#711 Provide docu metadata in gh-pages branch
  .travis.yml
Labels: REVIEW, documentation

#702 adding extensions to neoDeploy
  resources/default_pipeline_environment.yml
  src/com/sap/piper/tools/neo/NeoCommandHelper.groovy
  test/groovy/NeoDeployTest.groovy
  test/groovy/com/sap/piper/tools/neo/NeoCommandHelperTest.groovy
  vars/neoDeploy.groovy
Labels: REVIEW, enhancement
