Repository SAP/jenkins-library, pull requests merged in 2020-01, with the labels that each got.

#1091 Persisted pipeline environment for golang library
  DEVELOPMENT.md
  cmd/detectExecuteScan_generated.go
  cmd/getConfig.go
  cmd/githubCreatePullRequest_generated.go
  cmd/githubPublishRelease_generated.go
  cmd/karmaExecuteTests_generated.go
  cmd/piper.go
  cmd/version_generated.go
  cmd/xsDeploy_generated.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/resources.go
  pkg/config/stepmeta.go
  pkg/config/stepmeta_test.go
  pkg/generator/helper/helper.go
  pkg/generator/helper/helper_test.go
  pkg/generator/helper/resources.go
  pkg/generator/helper/resources_test.go
  pkg/generator/helper/testdata/TestProcessMetaFiles/step_code_generated.golden
  pkg/log/log.go
  pkg/piperenv/environment.go
  pkg/piperenv/environment_test.go
  resources/metadata/githubrelease.yaml
  test/groovy/CommonPipelineEnvironmentTest.groovy
  test/groovy/GithubPublishReleaseTest.groovy
  test/groovy/util/JenkinsFileExistsRule.groovy
  vars/commonPipelineEnvironment.groovy
  vars/githubPublishRelease.groovy
Labels: go-piper

#1106 improved Upload to handle http.Method
  pkg/http/http.go
  pkg/http/http_test.go
Labels: go-piper

#1103 Trim spaces from config value while reading CPE
  pkg/piperenv/environment.go
Labels: go-piper

#1102 Introduce support for different"interceptor API" in extensions
  test/groovy/PiperStageWrapperTest.groovy
  test/resources/stages/test_old_extension.groovy
  vars/artifactSetVersion.groovy
  vars/piperStageWrapper.groovy
Labels: REVIEW

#1073 Add kubernetesDeploy step
  Dockerfile
  cmd/getConfig.go
  cmd/getConfig_test.go
  cmd/interfaces.go
  cmd/kubernetesDeploy.go
  cmd/kubernetesDeploy_generated.go
  cmd/kubernetesDeploy_generated_test.go
  cmd/kubernetesDeploy_test.go
  cmd/piper.go
  cmd/piper_test.go
  pkg/command/command.go
  pkg/config/stepmeta.go
  pkg/config/stepmeta_test.go
  pkg/generator/helper/docuHelper.go
  pkg/generator/helper/helper.go
  pkg/generator/helper/helper_test.go
  resources/metadata/kubernetesdeploy.yaml
  test/groovy/CommonStepsTest.groovy
  test/groovy/KubernetesDeployTest.groovy
  vars/kubernetesDeploy.groovy
Labels: go-piper

#1075 Checkmarx as golang
  cmd/checkmarxExecuteScan.go
  cmd/checkmarxExecuteScan_generated.go
  cmd/checkmarxExecuteScan_generated_test.go
  cmd/checkmarxExecuteScan_test.go
  cmd/getConfig_test.go
  cmd/piper.go
  documentation/docs/steps/checkmarxExecuteScan.md
  go.mod
  go.sum
  pkg/checkmarx/checkmarx.go
  pkg/checkmarx/checkmarx_test.go
  pkg/config/flags.go
  pkg/config/stepmeta.go
  pkg/config/stepmeta_test.go
  pkg/http/http.go
  pkg/http/http_test.go
  pkg/piperutils/slices.go
  pkg/piperutils/slices_test.go
  pkg/piperutils/stepResults.go
  pkg/piperutils/stepResults_test.go
  resources/metadata/checkmarx.yaml
  src/com/sap/piper/JenkinsUtils.groovy
  test/groovy/CheckmarxExecuteScanTest.groovy
  test/groovy/CommonStepsTest.groovy
  vars/checkmarxExecuteScan.groovy
Labels: go-piper

#1069 fix(NPM): change NodeJS image to LTS
  cmd/karmaExecuteTests_generated.go
  resources/default_pipeline_environment.yml
  resources/metadata/karma.yaml
  test/groovy/BatsExecuteTestsTest.groovy
  test/groovy/GaugeExecuteTestsTest.groovy
  test/groovy/KarmaExecuteTestsTest.groovy
  test/groovy/NewmanExecuteTest.groovy
  test/groovy/NpmExecuteTest.groovy
  test/groovy/SeleniumExecuteTestsTest.groovy
  test/groovy/SnykExecuteTest.groovy
  test/groovy/SonarExecuteScanTest.groovy
  test/groovy/WhitesourceExecuteScanTest.groovy
  vars/karmaExecuteTests.groovy
  vars/npmExecute.groovy
Labels: ON HOLD

#1100 feat(go): add telemetry reporting
  Dockerfile
  cmd/checkmarxExecuteScan_generated.go
  cmd/detectExecuteScan_generated.go
  cmd/githubCreatePullRequest_generated.go
  cmd/githubPublishRelease_generated.go
  cmd/karmaExecuteTests_generated.go
  cmd/kubernetesDeploy_generated.go
  cmd/piper.go
  cmd/version_generated.go
  cmd/xsDeploy_generated.go
  go.mod
  go.sum
  pkg/generator/helper/helper.go
  pkg/generator/helper/testdata/TestProcessMetaFiles/step_code_generated.golden
  pkg/http/http.go
  pkg/telemetry/data.go
  pkg/telemetry/data_test.go
  pkg/telemetry/telemetry.go
  pkg/telemetry/telemetry_test.go
Labels: go-piper

#1117 re-use execRunner for envExecRunner
  cmd/interfaces.go
Labels: go-piper

#1113 Pass container image via CPE
  cmd/kubernetesDeploy_generated.go
  resources/metadata/kubernetesdeploy.yaml
  test/groovy/CommonPipelineEnvironmentTest.groovy
  vars/commonPipelineEnvironment.groovy
Labels: go-piper

#1133 Enhance telemetry reporting
  cmd/checkmarxExecuteScan_generated.go
  cmd/detectExecuteScan_generated.go
  cmd/githubCreatePullRequest_generated.go
  cmd/githubPublishRelease_generated.go
  cmd/karmaExecuteTests_generated.go
  cmd/kubernetesDeploy_generated.go
  cmd/version_generated.go
  cmd/xsDeploy_generated.go
  pkg/generator/helper/helper.go
  pkg/generator/helper/testdata/TestProcessMetaFiles/step_code_generated.golden
  pkg/telemetry/data.go
Labels: go-piper
