Repository SAP/jenkins-library, pull requests merged in 2020-08, with the labels that each got.

#1877 Update Go dependencies
  go.mod
  go.sum
Labels: REVIEW, go-piper

#1882 fix(step results): publish step results also on step error
  vars/piperExecuteBin.groovy
Labels: REVIEW

#1880 refactor(sonar): reuse piperExecuteBin code
  vars/piperExecuteBin.groovy
  vars/sonarExecuteScan.groovy
Labels: REVIEW

#1876 Improve testability of abap steps
  cmd/abapEnvironmentCheckoutBranch.go
  cmd/abapEnvironmentPullGitRepo.go
  cmd/abapEnvironmentPullGitRepo_test.go
  pkg/abaputils/abaputils.go
Labels: REVIEW

#1891 refactor(protecode): handle reports inside go
  cmd/protecodeExecuteScan.go
  vars/protecodeExecuteScan.groovy
Labels: REVIEW

#1886 refactor(protecode): reuse piperExecuteBin code
  vars/protecodeExecuteScan.groovy
Labels: ON HOLD, REVIEW

#1899 refactor(protecode): remove unused parameter
  cmd/protecodeExecuteScan_generated.go
  resources/metadata/protecode.yaml
Labels: REVIEW

#1896 docs: remove colons from headlines
  documentation/docs/steps/protecodeExecuteScan.md
Labels: REVIEW

#1875 Improve tests for cf steps
  cmd/cloudFoundryCreateServiceKey.go
  cmd/cloudFoundryCreateServiceKey_test.go
  cmd/cloudFoundryDeleteService.go
  cmd/cloudFoundryDeleteService_test.go
  pkg/cloudfoundry/Authentication.go
Labels: REVIEW

#1906 Add groovy wrapper for TemporaryCredentialsUtils
  documentation/docs/steps/writeTemporaryCredentials.md
  documentation/mkdocs.yml
  test/groovy/WriteTemporaryCredentialsTest.groovy
  vars/writeTemporaryCredentials.groovy
Labels: REVIEW

#1902 Rewrite nexus 3 Integration Tests
  integration/docker_integration_test_executor.go
  integration/integration_nexus_upload_test.go
Labels: REVIEW

#1905 docs: remove outdates prerequisites from Protecode step
  documentation/docs/steps/protecodeExecuteScan.md
Labels: REVIEW, documentation

#1911 chore(protecode): be more verbose about docker credentials
  cmd/protecodeExecuteScan.go
  cmd/protecodeExecuteScan_test.go
Labels: REVIEW

#1908 fortifyExecuteScan: Fix polling project status
  cmd/fortifyExecuteScan.go
  cmd/fortifyExecuteScan_test.go
Labels: REVIEW, bug :bug:, go-piper

#1909 Remove sapNpmRegistry
  cmd/mtaBuild.go
  cmd/mtaBuild_generated.go
  cmd/mtaBuild_test.go
  cmd/npmExecuteLint.go
  cmd/npmExecuteLint_generated.go
  cmd/npmExecuteLint_test.go
  cmd/npmExecuteScripts.go
  cmd/npmExecuteScripts_generated.go
  cmd/npmExecuteScripts_test.go
  integration/integration_npm_execute_scripts_test.go
  integration/testdata/TestNpmIntegration/registrySetInFlags/package.json
  integration/testdata/TestNpmIntegration/registrySetInNpmrc/.npmrc
  integration/testdata/TestNpmIntegration/registrySetInNpmrc/package.json
  integration/testdata/TestNpmIntegration/registryWithTwoModules/db/.npmrc
  integration/testdata/TestNpmIntegration/registryWithTwoModules/db/package.json
  integration/testdata/TestNpmIntegration/registryWithTwoModules/srv/package.json
  pkg/npm/npm.go
  pkg/npm/npm_test.go
  resources/metadata/mtaBuild.yaml
  resources/metadata/npmExecuteLint.yaml
  resources/metadata/npmExecuteScripts.yaml
Labels: REVIEW

#1900 fortifyExecuteScan: Make URL parameters more robust
  pkg/fortify/fortify.go
  pkg/fortify/fortify_test.go
Labels: REVIEW, bug :bug:

#1915 refactor(protecode): align Docker config.json parameter name
  resources/metadata/protecode.yaml
  vars/protecodeExecuteScan.groovy
Labels: REVIEW

#1914 refactor(protecode): add explicit parameter for Docker config.json file
  cmd/protecodeExecuteScan.go
  cmd/protecodeExecuteScan_generated.go
  cmd/protecodeExecuteScan_test.go
  documentation/docs/steps/protecodeExecuteScan.md
  resources/metadata/protecode.yaml
  vars/protecodeExecuteScan.groovy
Labels: REVIEW, documentation

#1922 Align stage name
  test/groovy/PiperStageWrapperTest.groovy
  vars/piperPipelineStageAcceptance.groovy
  vars/piperPipelineStageBuild.groovy
  vars/piperPipelineStageIntegration.groovy
  vars/piperPipelineStageRelease.groovy
  vars/piperStageWrapper.groovy
Labels: REVIEW

#1920 piper: Use stageName from parametersJSON, log value and source
  cmd/getConfig.go
  cmd/piper.go
  cmd/piper_test.go
Labels: REVIEW, enhancement, go-piper

#1927 Add mavenExecuteIntegration and writeTemporaryCredentials to piperPipelineStageIntegration
  resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
  resources/default_pipeline_environment.yml
  src/com/sap/piper/TemporaryCredentialsUtils.groovy
  test/groovy/WriteTemporaryCredentialsTest.groovy
  test/groovy/com/sap/piper/TemporaryCredentialsUtilsTest.groovy
  vars/piperPipelineStageIntegration.groovy
  vars/writeTemporaryCredentials.groovy
Labels: REVIEW

#1931 kubernetesDeploy - improve helm parameter handling
  cmd/kubernetesDeploy.go
  cmd/kubernetesDeploy_generated.go
  cmd/kubernetesDeploy_test.go
  resources/metadata/kubernetesdeploy.yaml
Labels: REVIEW

#1928 ABAP Pipeline documentation updates
  documentation/docs/pipelines/abapEnvironment/configuration.md
  documentation/docs/pipelines/abapEnvironment/introduction.md
Labels: REVIEW

#1935 cloudFoundryCreateService: Fix parameter scopes
  cmd/cloudFoundryCreateService_generated.go
  resources/metadata/cloudFoundryCreateService.yaml
Labels: REVIEW, bug :bug:, go-piper

#1952 Add optional wrapper for cloudFoundryDeploy go-implementation
  cmd/cloudFoundryDeploy.go
  cmd/cloudFoundryDeploy_generated.go
  cmd/cloudFoundryDeploy_test.go
  resources/metadata/cloudFoundryDeploy.yaml
  test/groovy/CloudFoundryDeployTest.groovy
  vars/cloudFoundryDeploy.groovy
  vars/commonPipelineEnvironment.groovy
Labels: REVIEW, go-piper

#1954 Add groovy file and documentation for cloneGitRepo step
  cmd/abapEnvironmentCloneGitRepo.go
  documentation/docs/steps/abapEnvironmentCloneGitRepo.md
  documentation/mkdocs.yml
  test/groovy/CommonStepsTest.groovy
  vars/abapEnvironmentCloneGitRepo.groovy
Labels: REVIEW

#1884 New step: abapEnvironmentAssemblePackages
  .gitignore
  cmd/abapEnvironmentAssemblePackages.go
  cmd/abapEnvironmentAssemblePackages_generated.go
  cmd/abapEnvironmentAssemblePackages_generated_test.go
  cmd/abapEnvironmentAssemblePackages_test.go
  cmd/piper.go
  documentation/docs/steps/abapEnvironmentAssemblePackages.md
  documentation/mkdocs.yml
  pkg/abaputils/abaputils.go
  pkg/abaputils/abaputils_test.go
  resources/metadata/abapEnvironmentAssemblePackages.yaml
  test/groovy/CommonStepsTest.groovy
  vars/abapEnvironmentAssemblePackages.groovy
Labels: ABAP, REVIEW

#1955 Extend conditions for step and stage activation
  resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
  test/groovy/PiperStageWrapperTest.groovy
  test/groovy/templates/PiperInitRunStageConfigurationTest.groovy
  vars/piperInitRunStageConfiguration.groovy
  vars/piperStageWrapper.groovy
Labels: REVIEW

#1959 Update Cloud SDK stage defaults
  resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
  vars/npmExecuteEndToEndTests.groovy
  vars/piperPipelineStageMavenStaticCodeChecks.groovy
Labels: REVIEW

#1962 Fix stageDefaults for fortify and mavenStaticCodeChecks
  resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
Labels: REVIEW

#1961 docs: link credentialIDs to parameter
  cmd/abapEnvironmentCheckoutBranch_generated.go
  cmd/abapEnvironmentCloneGitRepo_generated.go
  cmd/abapEnvironmentPullGitRepo_generated.go
  cmd/abapEnvironmentRunATCCheck_generated.go
  cmd/cloudFoundryCreateServiceKey_generated.go
  cmd/cloudFoundryCreateService_generated.go
  cmd/cloudFoundryDeleteService_generated.go
  cmd/cloudFoundryDeploy_generated.go
  cmd/fortifyExecuteScan_generated.go
  cmd/gctsCloneRepository_generated.go
  cmd/gctsCreateRepository_generated.go
  cmd/gctsDeploy_generated.go
  cmd/gctsExecuteABAPUnitTests_generated.go
  cmd/gctsRollback_generated.go
  cmd/githubCreatePullRequest_generated.go
  cmd/githubPublishRelease_generated.go
  cmd/kanikoExecute_generated.go
  cmd/kubernetesDeploy_generated.go
  cmd/malwareExecuteScan_generated.go
  cmd/nexusUpload_generated.go
  cmd/protecodeExecuteScan_generated.go
  cmd/whitesourceExecuteScan_generated.go
  cmd/xsDeploy_generated.go
  resources/metadata/abapEnvironmentCheckoutBranch.yaml
  resources/metadata/abapEnvironmentCloneGitRepo.yaml
  resources/metadata/abapEnvironmentPullGitRepo.yaml
  resources/metadata/abapEnvironmentRunATCCheck.yaml
  resources/metadata/cloudFoundryCreateService.yaml
  resources/metadata/cloudFoundryCreateServiceKey.yaml
  resources/metadata/cloudFoundryDeleteService.yaml
  resources/metadata/cloudFoundryDeploy.yaml
  resources/metadata/fortify.yaml
  resources/metadata/gctsCloneRepository.yaml
  resources/metadata/gctsCreateRepository.yaml
  resources/metadata/gctsDeployCommit.yaml
  resources/metadata/gctsExecuteABAPUnitTests.yaml
  resources/metadata/gctsRollback.yaml
  resources/metadata/githubcreatepr.yaml
  resources/metadata/githubrelease.yaml
  resources/metadata/kaniko.yaml
  resources/metadata/kubernetesdeploy.yaml
  resources/metadata/malwareExecuteScan.yaml
  resources/metadata/nexusUpload.yaml
  resources/metadata/protecode.yaml
  resources/metadata/whitesource.yaml
  resources/metadata/xsDeploy.yaml
Labels: REVIEW, documentation

#1933 Technical stage names
  src/com/sap/piper/StageNameProvider.groovy
  test/groovy/com/sap/piper/StageNameProviderTest.groovy
  test/groovy/templates/PiperPipelineStageAcceptanceTest.groovy
  test/groovy/templates/PiperPipelineStageAdditionalUnitTestsTest.groovy
  test/groovy/templates/PiperPipelineStageBuildTest.groovy
  test/groovy/templates/PiperPipelineStageInitTest.groovy
  test/groovy/templates/PiperPipelineStagePRVotingTest.groovy
  test/groovy/templates/PiperPipelineStagePostTest.groovy
  test/groovy/templates/PiperPipelineStagePromoteTest.groovy
  test/groovy/templates/PiperPipelineStageReleaseTest.groovy
  test/groovy/templates/PiperPipelineStageSecurityTest.groovy
  vars/piperPipelineStageAcceptance.groovy
  vars/piperPipelineStageAdditionalUnitTests.groovy
  vars/piperPipelineStageArtifactDeployment.groovy
  vars/piperPipelineStageBuild.groovy
  vars/piperPipelineStageCompliance.groovy
  vars/piperPipelineStageConfirm.groovy
  vars/piperPipelineStageInit.groovy
  vars/piperPipelineStageIntegration.groovy
  vars/piperPipelineStageMavenStaticCodeChecks.groovy
  vars/piperPipelineStagePRVoting.groovy
  vars/piperPipelineStagePerformance.groovy
  vars/piperPipelineStagePost.groovy
  vars/piperPipelineStagePromote.groovy
  vars/piperPipelineStageRelease.groovy
  vars/piperPipelineStageSecurity.groovy
Labels: REVIEW

#1966 Make protecodeExecuteScan tests run in temp dir
  cmd/protecodeExecuteScan_test.go
Labels: Code Quality, REVIEW

#1964 small docu change for mtar path
  vars/tmsUpload.groovy
Labels: documentation

#1965 refactor: correct yaml format
  resources/metadata/abapEnvironmentAssemblePackages.yaml
  resources/metadata/abapEnvironmentCheckoutBranch.yaml
  resources/metadata/abapEnvironmentCloneGitRepo.yaml
  resources/metadata/abapEnvironmentPullGitRepo.yaml
  resources/metadata/abapEnvironmentRunATCCheck.yaml
  resources/metadata/checkmarx.yaml
  resources/metadata/cloudFoundryCreateService.yaml
  resources/metadata/cloudFoundryCreateServiceKey.yaml
  resources/metadata/cloudFoundryDeleteService.yaml
  resources/metadata/cloudFoundryDeploy.yaml
  resources/metadata/detect.yaml
  resources/metadata/fortify.yaml
  resources/metadata/gctsCloneRepository.yaml
  resources/metadata/gctsCreateRepository.yaml
  resources/metadata/gctsDeployCommit.yaml
  resources/metadata/gctsExecuteABAPUnitTests.yaml
  resources/metadata/gctsRollback.yaml
  resources/metadata/githubcreatepr.yaml
  resources/metadata/githubrelease.yaml
  resources/metadata/kaniko.yaml
  resources/metadata/karma.yaml
  resources/metadata/kubernetesdeploy.yaml
  resources/metadata/malwareExecuteScan.yaml
  resources/metadata/mavenExecuteIntegration.yaml
  resources/metadata/mavenStaticCodeChecks.yaml
  resources/metadata/mtaBuild.yaml
  resources/metadata/nexusUpload.yaml
  resources/metadata/npmExecuteScripts.yaml
  resources/metadata/protecode.yaml
  resources/metadata/savecontainer.yaml
  resources/metadata/sonar.yaml
  resources/metadata/versioning.yaml
  resources/metadata/whitesource.yaml
  resources/metadata/xsDeploy.yaml
Labels: REVIEW
