Repository SAP/jenkins-library, pull requests merged in 2020-12, with the labels that each got.

#2443 fix(checksPublishResults): typo in tool it key
  vars/checksPublishResults.groovy
Labels: REVIEW

#2419 Remove input statement
  documentation/docs/pipelines/abapEnvironment/introduction.md
  vars/abapEnvironmentPipelineStagePrepareSystem.groovy
Labels: ABAP

#2441 Update Go dependencies
  go.mod
  go.sum
Labels: REVIEW, go-piper

#2448 fix(cfDeploy): correct stashing
  resources/metadata/cloudFoundryDeploy.yaml
  vars/cloudFoundryDeploy.groovy
Labels: REVIEW

#2437 piperExecuteBin: provide credentials directly without indirection into config
  test/groovy/PiperExecuteBinTest.groovy
  vars/piperExecuteBin.groovy
Labels: discussion

#2456 fix(cfDeploy): fix stash for go step
  vars/cloudFoundryDeploy.groovy
Labels: REVIEW

#2406 Don't allow empty strings as default container parameters
  pkg/config/stepmeta.go
  pkg/config/stepmeta_test.go
Labels: REVIEW, bug :bug:

#2463 fix(checks+tests): fail pipeline if plugins fail the build
  resources/default_pipeline_environment.yml
  vars/checksPublishResults.groovy
  vars/testsPublishResults.groovy
Labels: REVIEW

#2485 WS: Provide missing aliases
  cmd/whitesourceExecuteScan_generated.go
  resources/metadata/whitesource.yaml
Labels: REVIEW

#2466 chore: hide warning of verbose param during config resolve
  pkg/config/config.go
Labels: REVIEW
