Repository SAP/jenkins-library, pull requests merged in 2020-09, with the labels that each got.

#1969 fix(protecode): respect failOnSevereVulnerabilities parameter
  cmd/protecodeExecuteScan.go
  cmd/protecodeExecuteScan_test.go
  pkg/protecode/analysis.go
  pkg/protecode/analysis_test.go
  pkg/protecode/api.go
  pkg/protecode/protecode.go
  pkg/protecode/protecode_test.go
  pkg/protecode/report.go
  pkg/protecode/report_test.go
Labels: REVIEW

#1975 fix(protecode): correct project naming
  cmd/protecodeExecuteScan.go
  cmd/protecodeExecuteScan_test.go
Labels: REVIEW

#1976 Extend testsPublishResults step to support publishing of HTML reports
  resources/default_pipeline_environment.yml
  test/groovy/TestsPublishResultsTest.groovy
  vars/testsPublishResults.groovy
Labels: REVIEW

#1978 Add npmExecuteScripts to piperPipelineStageAdditionalUnitTests
  documentation/docs/pipelines/cloud-sdk/build-tools.md
  resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
  test/groovy/templates/PiperPipelineStageAdditionalUnitTestsTest.groovy
  vars/piperPipelineStageAdditionalUnitTests.groovy
Labels: REVIEW

#1979 Update Go dependencies
  go.mod
  go.sum
Labels: REVIEW, go-piper

#1986 Update Cloud SDK Pipeline docs on linting
  documentation/docs/extensibility.md
  documentation/docs/pipelines/cloud-sdk/build-tools.md
  documentation/docs/pipelines/cloud-sdk/cloud-qualities.md
Labels: REVIEW, documentation

#1985 Add npmExecuteLint and mavenExecuteStaticCodeChecks to build stage
  resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
  test/groovy/templates/PiperPipelineStageBuildTest.groovy
  vars/piperPipelineStageBuild.groovy
Labels: REVIEW

#1998 Fix for SonarQube: Remove check for non-productive branch
  vars/sonarExecuteScan.groovy
Labels: REVIEW, bug :bug:

#1984 docs: change secret docs
  pkg/generator/helper/docuHelper.go
  pkg/generator/helper/docuHelper_test.go
Labels: REVIEW, documentation

#1982 Extend sonarExecuteScan parameters
  cmd/sonarExecuteScan.go
  cmd/sonarExecuteScan_generated.go
  cmd/sonarExecuteScan_test.go
  resources/metadata/sonar.yaml
  vars/sonarExecuteScan.groovy
Labels: REVIEW, enhancement, go-piper

#2011 Rename frontendUnitTests to additionalUnitTests stage
  resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
Labels: REVIEW, sap-cloud-sdk

#2009 Fix runStep condition for mavenExecuteStaticCodeChecks
  cmd/mavenExecuteStaticCodeChecks.go
  cmd/mavenExecuteStaticCodeChecks_test.go
Labels: REVIEW, sap-cloud-sdk

#2017 Revert adding JaCoCo report paths to options
  cmd/sonarExecuteScan.go
  cmd/sonarExecuteScan_test.go
Labels: REVIEW, bug :bug:, go-piper

#1960 refactor: align parameter name for username
  cmd/nexusUpload.go
  cmd/nexusUpload_generated.go
  cmd/nexusUpload_test.go
  cmd/xsDeploy.go
  cmd/xsDeploy_generated.go
  cmd/xsDeploy_test.go
  integration/integration_nexus_upload_test.go
  resources/metadata/nexusUpload.yaml
  resources/metadata/xsDeploy.yaml
  test/groovy/XsDeployTest.groovy
  vars/nexusUpload.groovy
  vars/xsDeploy.groovy
Labels: REVIEW

#2025 fix(protecode): correct default value for excludeCVEs
  cmd/protecodeExecuteScan_generated.go
  resources/metadata/protecode.yaml
Labels: REVIEW

#2044 Fix: Avoid newline at end of timestamp in mtaBuild step
  cmd/mtaBuild.go
Labels: REVIEW

#2045 Add capabilities to check for breaking changes in config
  resources/com.sap.piper/pipeline/cloudSdkLegacyConfigSettings.yml
  src/com/sap/piper/LegacyConfigurationCheckUtils.groovy
  test/groovy/com/sap/piper/LegacyConfigurationCheckUtilsTest.groovy
Labels: REVIEW, enhancement

#1993 dockerExecuteOnKubernetes: Make container limits configurable
  test/groovy/DockerExecuteOnKubernetesTest.groovy
  vars/dockerExecuteOnKubernetes.groovy
Labels: REVIEW

#2033 refactor(docs): separate step and docs generator
  .github/workflows/documentation.yaml
  integration/contracts_test.go
  pkg/documentation/generator.go
  pkg/documentation/generator/defaults.go
  pkg/documentation/generator/defaults_test.go
  pkg/documentation/generator/description.go
  pkg/documentation/generator/helper.go
  pkg/documentation/generator/main.go
  pkg/documentation/generator/main_test.go
  pkg/documentation/generator/outputs.go
  pkg/documentation/generator/outputs_test.go
  pkg/documentation/generator/parameters.go
  pkg/documentation/generator/parameters_test.go
  pkg/generator/helper/docuHelper.go
  pkg/generator/helper/goUtils.go
  pkg/generator/helper/helper.go
  pkg/generator/helper/helper_test.go
  pkg/generator/step-metadata.go
Labels: REVIEW, documentation

#2065 chore(go): simplify code using gofmt -s
  cmd/abapEnvironmentRunATCCheck_test.go
  cmd/checkmarxExecuteScan.go
  cmd/checkmarxExecuteScan_test.go
  cmd/cloudFoundryCreateService_test.go
  cmd/cloudFoundryDeploy_test.go
  cmd/gctsExecuteABAPUnitTests_test.go
  cmd/kanikoExecute.go
  integration/integration_cli_test.go
  pkg/cloudfoundry/CloudFoundry_test.go
  pkg/config/config_test.go
  pkg/config/stepmeta_test.go
  pkg/config/vault_test.go
  pkg/http/http_test.go
  pkg/piperutils/stepResults_test.go
  pkg/protecode/protecode.go
  pkg/versioning/pip_test.go
  pkg/yaml/yamlUtil_test.go
Labels: Code Quality, REVIEW

#2049 Add steps for cf space creation and deletion
  cmd/cloudFoundryCreateSpace.go
  cmd/cloudFoundryCreateSpace_generated.go
  cmd/cloudFoundryCreateSpace_generated_test.go
  cmd/cloudFoundryCreateSpace_test.go
  cmd/cloudFoundryDeleteSpace.go
  cmd/cloudFoundryDeleteSpace_generated.go
  cmd/cloudFoundryDeleteSpace_generated_test.go
  cmd/cloudFoundryDeleteSpace_test.go
  cmd/piper.go
  documentation/docs/steps/cloudFoundryCreateSpace.md
  documentation/docs/steps/cloudFoundryDeleteSpace.md
  resources/metadata/cloudFoundryCreateSpace.yaml
  resources/metadata/cloudFoundryDeleteSpace.yaml
  test/groovy/CommonStepsTest.groovy
  vars/cloudFoundryCreateSpace.groovy
  vars/cloudFoundryDeleteSpace.groovy
Labels: REVIEW, feature

#2077 docs: use correct template library
  pkg/documentation/generator/main.go
Labels: documentation

#2062 Extend piperPipelineStageInit to support init of Cloud SDK
  resources/com.sap.piper/pipeline/cloudSdkContainersMap.yml
  resources/com.sap.piper/pipeline/cloudSdkJavaStashSettings.yml
  resources/com.sap.piper/pipeline/cloudSdkJavascriptStashSettings.yml
  resources/com.sap.piper/pipeline/cloudSdkMtaStashSettings.yml
  test/groovy/templates/PiperPipelineStageInitTest.groovy
  vars/piperPipelineStageInit.groovy
Labels: REVIEW, sap-cloud-sdk

#2078 docs: add note about Jenkins credentials
  pkg/documentation/generator/parameters.go
Labels: documentation

#2081 Update Cloud SDK documentation
  documentation/docs/pipelines/cloud-sdk/configuration.md
  documentation/docs/steps/debugReportArchive.md
  documentation/mkdocs.yml
  resources/com.sap.piper/pipeline/cloudSdkLegacyConfigSettings.yml
Labels: documentation, sap-cloud-sdk

#2082 Preparation to switch to piperPipelineStageSecurity for Cloud SDK pipeline
  documentation/docs/pipelines/cloud-sdk/configuration.md
  resources/com.sap.piper/pipeline/cloudSdkContainersMap.yml
  resources/com.sap.piper/pipeline/cloudSdkJavaStashSettings.yml
  resources/com.sap.piper/pipeline/cloudSdkJavascriptStashSettings.yml
  resources/com.sap.piper/pipeline/cloudSdkLegacyConfigSettings.yml
  resources/com.sap.piper/pipeline/cloudSdkMtaStashSettings.yml
  resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
Labels: REVIEW, sap-cloud-sdk

#1879 whitesourceExecuteScan: bypass UA for mta, maven, npm and yarn
  cmd/whitesourceExecuteScan.go
  cmd/whitesourceExecuteScan_test.go
  pkg/maven/model.go
  pkg/maven/model_test.go
  pkg/mock/fileUtils.go
  pkg/mock/fileUtils_test.go
  pkg/piperutils/slices.go
  pkg/piperutils/slices_test.go
  pkg/versioning/versioning.go
  pkg/versioning/versioning_test.go
  pkg/versioning/yamlfile.go
  resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
  resources/metadata/mavenBuild.yaml
Labels: Code Quality, enhancement, go-piper

#2089 Remove absolute links from Cloud SDK docs section
  documentation/docs/pipelines/cloud-sdk/build-tools.md
  documentation/docs/pipelines/cloud-sdk/cloud-qualities.md
  documentation/docs/pipelines/cloud-sdk/configuration.md
Labels: REVIEW, documentation, sap-cloud-sdk

#2097 Fix conditions for whitesourceExecuteScan
  resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
Labels: REVIEW, bug :bug:

#2095 fix: make unstash work for parallel executions
  src/com/sap/piper/Utils.groovy
Labels: REVIEW

#2067 [refactoring] Avoid having simiar dockerExecuteOnKubernetes call twice.
  vars/dockerExecute.groovy
Labels: REVIEW

#2092 docs: make used library and binary name in samples exchangeable
  pkg/documentation/generator.go
  pkg/documentation/generator/description.go
  pkg/documentation/generator/description_test.go
Labels: REVIEW
