Repository SAP/jenkins-library, pull requests merged in 2020-06, with the labels that each got.

#1616 Needed CLI separator for Fortify tools depends on platform
  cmd/fortifyExecuteScan.go
  cmd/fortifyExecuteScan_generated.go
  cmd/fortifyExecuteScan_test.go
  resources/metadata/fortify.yaml
Labels: REVIEW, go-piper

#1606 Provide an ExecRunner implementation for running commands in docker
  pkg/mock/dockerRunner.go
  pkg/mock/dockerRunner_test.go
  pkg/mock/example_dockerRunner_test.go
Labels: REVIEW, go-piper

#1629 Fix: yaml util handling for boolean with value false
  src/com/sap/piper/variablesubstitution/YamlUtils.groovy
  test/groovy/CfManifestSubstituteVariablesTest.groovy
  test/groovy/com/sap/piper/variablesubstitution/YamlUtilsTest.groovy
  test/resources/variableSubstitution/datatypes_manifest-variables.yml
  test/resources/variableSubstitution/datatypes_manifest.yml
Labels: bug :bug:

#1630 Update Go dependencies
  go.mod
  go.sum
Labels: REVIEW, go-piper

#1622 Use go-based npmExecuteScripts, mavenBuild in buildExecute
  resources/default_pipeline_environment.yml
  test/groovy/BuildExecuteTest.groovy
  vars/buildExecute.groovy
Labels: REVIEW

#1634 Fix running artifactPrepareVersion in maven container if necessary
  cmd/artifactPrepareVersion_generated.go
  documentation/docs/pipelines/cloud-sdk/build-tools.md
  resources/metadata/versioning.yaml
  vars/artifactPrepareVersion.groovy
  vars/dockerExecute.groovy
  vars/dockerExecuteOnKubernetes.groovy
  vars/piperExecuteBin.groovy
Labels: REVIEW, go-piper

#1645 Store build tool in commonPipelineEnvironment
  vars/buildExecute.groovy
  vars/commonPipelineEnvironment.groovy
Labels: REVIEW

#1633 emit used project config & defaults to log
  cmd/piper.go
Labels: REVIEW

#1648 Increase default transport timeout to 3 mins
  pkg/http/http.go
  pkg/http/http_test.go
Labels: REVIEW, go-piper

#1659 Refactor maven.Evaluate() to take options
  cmd/nexusUpload.go
  cmd/nexusUpload_test.go
  pkg/maven/maven.go
  pkg/maven/maven_test.go
  pkg/versioning/maven.go
  pkg/versioning/maven_test.go
  pkg/versioning/versioning.go
  pkg/versioning/versioning_test.go
Labels: REVIEW, go-piper

#1655 Fix scoping of variable in checkmarx scan
  cmd/checkmarxExecuteScan.go
Labels: go-piper

#1325 fetch xsuaa credentials in newman execution
  src/com/sap/piper/integration/CloudFoundry.groovy
  test/groovy/NewmanExecuteTest.groovy
  test/groovy/com/sap/piper/integration/CloudFoundryTest.groovy
  vars/newmanExecute.groovy
Labels: REVIEW

#1657 doc(kubernetes): Make plugin link clickable
  vars/dockerExecuteOnKubernetes.groovy
Labels: documentation

#1641 Install maven artifacts after mta build
  cmd/mtaBuild.go
  cmd/mtaBuild_generated.go
  integration/integration_mta_build_test.go
  integration/run-tests.sh
  integration/testdata/TestMtaIntegration/maven/.gitignore
  integration/testdata/TestMtaIntegration/maven/Dockerfile
  integration/testdata/TestMtaIntegration/maven/app/Foo.java
  integration/testdata/TestMtaIntegration/maven/app/pom.xml
  integration/testdata/TestMtaIntegration/maven/cleanup.sh
  integration/testdata/TestMtaIntegration/maven/mta.yaml
  integration/testdata/TestMtaIntegration/maven/pom.xml
  integration/testdata/TestMtaIntegration/maven/run-in-container.sh
  integration/testdata/TestMtaIntegration/maven/run.sh
  integration/testdata/TestMtaIntegration/npm/.gitignore
  integration/testdata/TestMtaIntegration/npm/Dockerfile
  integration/testdata/TestMtaIntegration/npm/cleanup.sh
  integration/testdata/TestMtaIntegration/npm/gen/srv/.gitkeep
  integration/testdata/TestMtaIntegration/npm/mta.yaml
  integration/testdata/TestMtaIntegration/npm/package.json
  integration/testdata/TestMtaIntegration/npm/run-in-container.sh
  integration/testdata/TestMtaIntegration/npm/run.sh
  integration/testdata/TestMtaIntegration/npm/srv/hello.js
  integration/testdata/TestMtaIntegration/npm/test/integration-tests/helloworld.spec.js
  integration/testdata/TestMtaIntegration/npm/test/unit-tests/helloworld.spec.js
  pkg/maven/maven.go
  pkg/maven/maven_test.go
  resources/metadata/mtaBuild.yaml
Labels: REVIEW

#1654 GithubPublishRelease: Add "pre-release" flag
  cmd/githubPublishRelease.go
  cmd/githubPublishRelease_generated.go
  cmd/githubPublishRelease_test.go
  resources/metadata/githubrelease.yaml
Labels: REVIEW

#1593 chore(pipeline): add action to lint markdown files
  .github/workflows/markdown.yml
  .markdownlint.yml
Labels: REVIEW

#1670 Consider stage config from custom defaults
  pkg/config/config.go
  pkg/config/config_test.go
Labels: REVIEW, bug :bug:, go-piper

#1669 Run npm scripts in virtual frame buffer and extend command.go to run executable asynchronously
  cmd/fortifyExecuteScan.go
  cmd/interfaces.go
  cmd/npmExecuteScripts.go
  cmd/npmExecuteScripts_generated.go
  cmd/npmExecuteScripts_test.go
  pkg/command/command.go
  pkg/command/execution.go
  pkg/mock/runner.go
  resources/metadata/npmExecuteScripts.yaml
Labels: REVIEW, enhancement, go-piper

#1608 Introduce manifest utils for cf
  pkg/cloudfoundry/ManifestUtils.go
  pkg/cloudfoundry/ManifestUtils_test.go
Labels: REVIEW

#1674 Add npmExecuteScripts to integration stage
  test/groovy/templates/PiperPipelineStageAcceptanceTest.groovy
  test/groovy/templates/PiperPipelineStageAdditionalUnitTestsTest.groovy
  test/groovy/templates/PiperPipelineStageIntegrationTest.groovy
  test/groovy/templates/PiperPipelineStagePRVotingTest.groovy
  test/groovy/templates/PiperPipelineStagePostTest.groovy
  test/groovy/templates/PiperPipelineStagePromoteTest.groovy
  test/groovy/templates/PiperPipelineStageReleaseTest.groovy
  test/groovy/templates/PiperPipelineStageSecurityTest.groovy
  vars/piperPipelineStageIntegration.groovy
  vars/piperStageWrapper.groovy
Labels: REVIEW, enhancement

#1468 Introducing new step 'gctsCloneRepository'
  cmd/gctsCloneRepository.go
  cmd/gctsCloneRepository_generated.go
  cmd/gctsCloneRepository_generated_test.go
  cmd/gctsCloneRepository_test.go
  cmd/piper.go
  documentation/docs/steps/gctsCloneRepository.md
  resources/metadata/gctsCloneRepository.yaml
  test/groovy/CommonStepsTest.groovy
  vars/gctsCloneRepository.groovy
Labels: ABAP, REVIEW

#1595 remove library statement from piperPipeline
  vars/piperPipeline.groovy
Labels: REVIEW

#1680 Add ability to load custom defaults from secured resource
  vars/setupCommonPipelineEnvironment.groovy
Labels: REVIEW, enhancement

#1683 Add schema patch step in go
  cmd/jsonApplyPatch.go
  cmd/jsonApplyPatch_generated.go
  cmd/jsonApplyPatch_generated_test.go
  cmd/jsonApplyPatch_test.go
  cmd/piper.go
  go.mod
  go.sum
  resources/metadata/jsonApplyPatch.yaml
Labels: REVIEW, go-piper

#1682 chore(readme): add go report badge
  README.md
Labels: REVIEW

#1689 Make version command a high level command like get-config without resolving the configuration
  cmd/version.go
  cmd/version_generated.go
  cmd/version_generated_test.go
  cmd/version_test.go
  resources/metadata/version.yaml
Labels: REVIEW, go-piper

#1691 Add sysadmin capabilities to npmExecuteScripts
  vars/npmExecuteScripts.groovy
Labels: REVIEW

#1694 Let json patcher fail if file not found
  cmd/jsonApplyPatch.go
  cmd/jsonApplyPatch_test.go
Labels: REVIEW

#1636 Add Java-/Typescript linting capabilities
  cmd/npmExecuteLint.go
  cmd/npmExecuteLint_generated.go
  cmd/npmExecuteLint_generated_test.go
  cmd/npmExecuteLint_test.go
  cmd/npmExecuteScripts_test.go
  cmd/piper.go
  documentation/docs/pipelines/cloud-sdk/build-tools.md
  documentation/docs/steps/npmExecuteLint.md
  documentation/mkdocs.yml
  resources/.eslintrc.json
  resources/metadata/npmExecuteLint.yaml
  test/groovy/CommonStepsTest.groovy
  vars/npmExecuteLint.groovy
Labels: REVIEW, feature, go-piper

#1685 Install dev deps in mta build
  cmd/mtaBuild.go
  cmd/mtaBuild_generated.go
  integration/integration_mta_build_test.go
  integration/testdata/TestMtaIntegration/maven/.gitignore
  integration/testdata/TestMtaIntegration/maven/app/package.json
  integration/testdata/TestMtaIntegration/npm-install-dev-dependencies/.gitignore
  integration/testdata/TestMtaIntegration/npm-install-dev-dependencies/cleanup.sh
  integration/testdata/TestMtaIntegration/npm-install-dev-dependencies/mta.yaml
  integration/testdata/TestMtaIntegration/npm-install-dev-dependencies/package.json
  resources/metadata/mtaBuild.yaml
Labels: REVIEW, go-piper

#1688 Load global extensions in setupCommonPipelineEnvironment
  documentation/docs/steps/piperLoadGlobalExtensions.md
  documentation/mkdocs.yml
  resources/default_pipeline_environment.yml
  test/groovy/PiperLoadGlobalExtensionsTest.groovy
  test/groovy/PiperStageWrapperTest.groovy
  vars/piperLoadGlobalExtensions.groovy
  vars/setupCommonPipelineEnvironment.groovy
Labels: REVIEW

#1699 fix(influx): pass Sonar token to influx
  vars/influxWriteData.groovy
Labels: REVIEW

#1555 Add ABAP Environment Pipeline
  documentation/docs/pipelines/abapEnvironment/introduction.md
  documentation/mkdocs.yml
  resources/com.sap.piper/pipeline/abapStageDefaults.yml
  resources/com.sap.piper/pipeline/abapStageOrdinals.yml
  resources/com.sap.piper/pipeline/abapStashSettings.yml
  test/groovy/CommonStepsTest.groovy
  test/groovy/templates/AbapEnvironmentPipelineStageInitTest.groovy
  test/groovy/templates/AbapEnvironmentPipelineStagePostTest.groovy
  test/groovy/templates/AbapEnvironmentPipelineStagePrepareSystemTest.groovy
  test/groovy/templates/AbapEnvironmentPipelineTest.groovy
  vars/abapEnvironmentPipeline.groovy
  vars/abapEnvironmentPipelineStageATC.groovy
  vars/abapEnvironmentPipelineStageCloneRepositories.groovy
  vars/abapEnvironmentPipelineStageInit.groovy
  vars/abapEnvironmentPipelineStagePost.groovy
  vars/abapEnvironmentPipelineStagePrepareSystem.groovy
Labels: ABAP, REVIEW

#1698 fix: remove unused variables from generated step coding
  cmd/abapEnvironmentPullGitRepo_generated.go
  cmd/abapEnvironmentRunATCCheck_generated.go
  cmd/artifactPrepareVersion_generated.go
  cmd/checkmarxExecuteScan_generated.go
  cmd/cloudFoundryCreateServiceKey_generated.go
  cmd/cloudFoundryDeleteService_generated.go
  cmd/containerSaveImage_generated.go
  cmd/detectExecuteScan_generated.go
  cmd/fortifyExecuteScan_generated.go
  cmd/gctsCloneRepository_generated.go
  cmd/gctsCreateRepository_generated.go
  cmd/gctsDeploy_generated.go
  cmd/githubCreatePullRequest_generated.go
  cmd/githubPublishRelease_generated.go
  cmd/jsonApplyPatch_generated.go
  cmd/karmaExecuteTests_generated.go
  cmd/kubernetesDeploy_generated.go
  cmd/malwareExecuteScan_generated.go
  cmd/mavenBuild_generated.go
  cmd/mavenExecuteStaticCodeChecks_generated.go
  cmd/mavenExecute_generated.go
  cmd/mtaBuild_generated.go
  cmd/nexusUpload_generated.go
  cmd/npmExecuteLint_generated.go
  cmd/npmExecuteScripts_generated.go
  cmd/protecodeExecuteScan_generated.go
  cmd/sonarExecuteScan_generated.go
  cmd/xsDeploy_generated.go
  pkg/generator/helper/helper.go
  pkg/generator/helper/resources.go
  pkg/generator/helper/testdata/TestProcessMetaFiles/custom_step_code_generated.golden
  pkg/generator/helper/testdata/TestProcessMetaFiles/step_code_generated.golden
Labels: REVIEW

#1707 fix(security): remove duplicate stage wrapper
  vars/piperPipelineStageSecurity.groovy
Labels: REVIEW

#670 add parallel execution to multicloudDeploy
  resources/default_pipeline_environment.yml
  src/com/sap/piper/Utils.groovy
  test/groovy/MulticloudDeployTest.groovy
  vars/commonPipelineEnvironment.groovy
  vars/multicloudDeploy.groovy
  vars/neoDeploy.groovy
Labels: REVIEW

#1714 Fix extensions for Post stage of ABAP Pipeline
  resources/com.sap.piper/pipeline/abapStashSettings.yml
Labels: REVIEW

#1719 Fix error Handling in DefaultValueCache
  src/com/sap/piper/DefaultValueCache.groovy
Labels: REVIEW, bug :bug:
