Repository SAP/jenkins-library, pull requests merged in 2020-02, with the labels that each got.

#1126 Add DebugReport facility
  resources/debug_report.txt
  src/com/sap/piper/DebugReport.groovy
  test/groovy/HandlePipelineStepErrorsTest.groovy
  test/groovy/PiperStageWrapperTest.groovy
  test/groovy/com/sap/piper/DebugReportTest.groovy
  test/resources/stages/test_global_overwriting.groovy
  vars/handlePipelineStepErrors.groovy
  vars/piperStageWrapper.groovy
Labels: REVIEW

#1143 Added EnvironmentUtils needed by DebugReport (#1126)
  src/com/sap/piper/DebugReport.groovy
  src/com/sap/piper/EnvironmentUtils.groovy
  test/groovy/com/sap/piper/EnvironmentUtilsTest.groovy
Labels: REVIEW

#1107 Go implementation for abapEnvironmentPullGitRepo()
  cmd/abapEnvironmentPullGitRepo.go
  cmd/abapEnvironmentPullGitRepo_generated.go
  cmd/abapEnvironmentPullGitRepo_generated_test.go
  cmd/abapEnvironmentPullGitRepo_test.go
  cmd/piper.go
  documentation/docs/steps/abapEnvironmentPullGitRepo.md
  pkg/http/http.go
  resources/metadata/abapEnvironmentPullGitRepo.yaml
  test/groovy/AbapEnvironmentPullGitRepoTest.groovy
  test/groovy/CommonStepsTest.groovy
  vars/abapEnvironmentPullGitRepo.groovy
Labels: go-piper

#1146 Executing extensions in handlePipelineStepErrors
  test/groovy/PiperStageWrapperTest.groovy
  test/resources/stages/test_crashing_extension.groovy
  vars/piperStageWrapper.groovy
Labels: REVIEW

#1155 Provide docker functionality
  go.mod
  go.sum
  pkg/docker/docker.go
  pkg/docker/docker_test.go
Labels: go-piper, work in progress 🚧

#1156 Docker functionality fix interface
  pkg/docker/docker.go
Labels: go-piper

#1119 Protecode as GoLang
  .gitignore
  cmd/piper.go
  cmd/protecodeExecuteScan.go
  cmd/protecodeExecuteScan_generated.go
  cmd/protecodeExecuteScan_generated_test.go
  cmd/protecodeExecuteScan_test.go
  cmd/testdata/TestProtecode/protecode_result_violations.json
  documentation/docs/steps/protecodeExecuteScan.md
  pkg/http/http.go
  pkg/protecode/protecode.go
  pkg/protecode/protecode_test.go
  pkg/protecode/testdata/protecode_result_no_violations.json
  pkg/protecode/testdata/protecode_result_triaging.json
  pkg/protecode/testdata/protecode_result_violations.json
  pom.xml
  resources/metadata/protecode.yaml
  src/com/sap/piper/JenkinsUtils.groovy
  test/groovy/CommonStepsTest.groovy
  test/groovy/com/sap/piper/JenkinsUtilsTest.groovy
  vars/protecodeExecuteScan.groovy
Labels: go-piper, work in progress 🚧

#1161 adjust protecode influx parameter
  cmd/protecodeExecuteScan.go
  cmd/protecodeExecuteScan_generated.go
  resources/metadata/protecode.yaml
Labels: go-piper

#1152 Implement archiving the debug report as step
  resources/debug_report.txt
  resources/default_pipeline_environment.yml
  src/com/sap/piper/DebugReport.groovy
  test/groovy/DebugReportArchiveTest.groovy
  test/groovy/com/sap/piper/DebugReportTest.groovy
  vars/debugReportArchive.groovy
Labels: REVIEW

#1160 Disable or fail on blue green deployment if not supported by manifest structure
  test/groovy/CloudFoundryDeployTest.groovy
  vars/cloudFoundryDeploy.groovy
Labels: REVIEW

#1162 Pass stageName to dockerExecuteOnKubernetes
  vars/piperStageWrapper.groovy
Labels: REVIEW

#1097 Add step cloudFoundryDeleteService
  cmd/cloudFoundryDeleteService.go
  cmd/cloudFoundryDeleteService_generated.go
  cmd/cloudFoundryDeleteService_generated_test.go
  cmd/cloudFoundryDeleteService_test.go
  cmd/piper.go
  documentation/docs/steps/cloudFoundryDeleteService.md
  documentation/mkdocs.yml
  resources/metadata/cloudFoundryDeleteService.yaml
  test/groovy/CommonStepsTest.groovy
  vars/cloudFoundryDeleteService.groovy
Labels: go-piper

#1127 [refactoring] Condence common functions for execRunner and shellRunne…
  cmd/interfaces.go
Labels: go-piper

#1175 Adjust documentation for Protecode
  cmd/protecodeExecuteScan_generated.go
  resources/metadata/protecode.yaml
Labels: documentation, go-piper

#1184 Fixed error handling gitHubPublishRelease
  cmd/githubPublishRelease.go
  cmd/githubPublishRelease_test.go
Labels: bug :bug:, go-piper

#1165 Document how pipelines can be more flexible
  documentation/docs/extensibility.md
  documentation/docs/images/customPipelineLib.png
  documentation/docs/images/levels-of-extensibility.png
  documentation/docs/index.md
Labels: REVIEW

#1186 Fix broken link
  documentation/docs/index.md
Labels: MERGE, REVIEW, documentation

#1188 Update generator
  pkg/generator/helper/helper.go
Labels: go-piper

#1131 Provide foundation for integration-like tests
  .codeclimate.yml
  .github/workflows/verify-go.yml
  go.mod
  go.sum
  integration/contracts_test.go
  integration/integration_api_cli_test.go
  integration/integration_api_test.go
  integration/integration_cli_test.go
  integration/integration_test.go
  integration/testdata/TestKarmaIntegration/karma.conf.js
  integration/testdata/TestKarmaIntegration/package.json
  integration/testdata/TestKarmaIntegration/src/frontend/Component.js
  integration/testdata/TestKarmaIntegration/src/frontend/controller/App.controller.js
  integration/testdata/TestKarmaIntegration/src/frontend/index.html
  integration/testdata/TestKarmaIntegration/src/frontend/test/integration/AllJourneys.js
  integration/testdata/TestKarmaIntegration/src/frontend/test/integration/navigation.js
  integration/testdata/TestKarmaIntegration/src/frontend/test/integration/opaTests.qunit.html
  integration/testdata/TestKarmaIntegration/src/frontend/test/integration/pages/App.js
  integration/testdata/TestKarmaIntegration/src/frontend/test/integration/pages/Common.js
  integration/testdata/TestKarmaIntegration/src/frontend/test/karma-qunit.js
  integration/testdata/TestKarmaIntegration/src/frontend/view/App.view.xml
  integration/testdata/TestKarmaIntegration/src/frontend/view/Dialog.fragment.xml
Labels: REVIEW, go-piper

#1167 Move docs of Cloud SDK Pipeline into this repo
  documentation/docs/pipelines/cloud-sdk/build-tools.md
  documentation/docs/pipelines/cloud-sdk/cloud-qualities.md
  documentation/docs/pipelines/cloud-sdk/introduction.md
  documentation/docs/pipelines/cloud-sdk/shared-config-between-projects.md
  documentation/mkdocs.yml
Labels: REVIEW, documentation

#1191 Streamline implementation githubPublishRelease
  resources/metadata/githubrelease.yaml
  test/groovy/GithubPublishReleaseTest.groovy
  vars/githubPublishRelease.groovy
Labels: go-piper

#1203 switch downloader from POST to GET
  pkg/http/downloader.go
Labels: go-piper

#1120 unify mocking for shell and exec runner
  cmd/detectExecuteScan_test.go
  cmd/karmaExecuteTests_test.go
  cmd/piper_test.go
  cmd/xsDeploy_test.go
Labels: REVIEW, go-piper

#1209 Add 'Code generated by' header to stepGoTemplate
  cmd/abapEnvironmentPullGitRepo_generated.go
  cmd/checkmarxExecuteScan_generated.go
  cmd/cloudFoundryDeleteService_generated.go
  cmd/detectExecuteScan_generated.go
  cmd/githubCreatePullRequest_generated.go
  cmd/githubPublishRelease_generated.go
  cmd/karmaExecuteTests_generated.go
  cmd/kubernetesDeploy_generated.go
  cmd/protecodeExecuteScan_generated.go
  cmd/version_generated.go
  cmd/xsDeploy_generated.go
  pkg/generator/helper/helper.go
  pkg/generator/helper/testdata/TestProcessMetaFiles/custom_step_code_generated.golden
  pkg/generator/helper/testdata/TestProcessMetaFiles/step_code_generated.golden
Labels: REVIEW, go-piper

#855 Upload to transport request scenario
  documentation/docs/scenarios/upload-to-transportrequest/Readme.md
  documentation/docs/scenarios/upload-to-transportrequest/files/mta.yaml
  documentation/docs/scenarios/upload-to-transportrequest/images/pipeline.png
  documentation/mkdocs.yml
Labels: documentation

#1215 Add '**/*_generated*.go' to exclude patterns for codeclimate
  .codeclimate.yml
Labels: REVIEW, go-piper

#1176 Settings file handling (prepares mtaBuild step)
  pkg/maven/settings.go
  pkg/maven/settings_test.go
  pkg/piperutils/FileUtils.go
Labels: REVIEW, go-piper

#1128 go: mta build
  cmd/mtaBuild.go
  cmd/mtaBuild_generated.go
  cmd/mtaBuild_generated_test.go
  cmd/mtaBuild_test.go
  cmd/piper.go
  cmd/xsDeploy.go
  cmd/xsDeploy_test.go
  go.mod
  resources/metadata/mtaBuild.yaml
Labels: REVIEW, go-piper

#1206 Support nested folders when performing a http download into a file
  pkg/http/downloader.go
  pkg/http/downloader_test.go
Labels: REVIEW, go-piper

#1192 Utils.evaluateFromMavenPom(): Handle errors
  src/com/sap/piper/Utils.groovy
Labels: REVIEW

#1207 Add revive config for proper linting
  config.toml
Labels: REVIEW

#1226 Move mock capabilities to pkg/mock/runner and adapt all tests
  cmd/abapEnvironmentPullGitRepo_test.go
  cmd/cloudFoundryDeleteService_test.go
  cmd/detectExecuteScan.go
  cmd/detectExecuteScan_test.go
  cmd/interfaces.go
  cmd/karmaExecuteTests.go
  cmd/karmaExecuteTests_test.go
  cmd/kubernetesDeploy.go
  cmd/kubernetesDeploy_test.go
  cmd/mtaBuild.go
  cmd/mtaBuild_test.go
  cmd/piper_test.go
  cmd/xsDeploy_test.go
  integration/integration_api_test.go
  integration/integration_cli_test.go
  pkg/command/command.go
  pkg/mock/runner.go
Labels: REVIEW, go-piper

#1232 Add tag release when building go binary
  .github/workflows/verify-go.yml
  Dockerfile
  pkg/mock/runner.go
Labels: REVIEW, go-piper

#1189 Fix documentation for XSA
  documentation/docs/scenarios/xsa-deploy/Readme.md
Labels: documentation

#1109 xs deploy: check for operation id in go layer
  cmd/xsDeploy.go
  cmd/xsDeploy_test.go
Labels: REVIEW, go-piper

#1111 xs deploy cpe inputs and outputs
  cmd/xsDeploy.go
  cmd/xsDeploy_generated.go
  cmd/xsDeploy_test.go
  resources/metadata/xsDeploy.yaml
Labels: REVIEW, go-piper

#1211 xsDeploy: simplifiy assertions in tests
  cmd/xsDeploy_test.go
Labels: go-piper

#1204 Add mavenExecute to go lib
  cmd/mavenExecute.go
  cmd/mavenExecute_generated.go
  cmd/mavenExecute_generated_test.go
  cmd/piper.go
  pkg/maven/maven.go
  pkg/maven/maven_test.go
  resources/metadata/maven.yaml
Labels: REVIEW, go-piper
