Repository SAP/jenkins-library, pull requests merged in 2020-11, with the labels that each got.

#2222 generator: Don't swallow output from go fmt
  pkg/generator/step-metadata.go
Labels: REVIEW

#2261 Avoid CPS serialization issue in setupCPE
  test/groovy/FioriOnCloudPlatformPipelineTest.groovy
  test/groovy/SetupCommonPipelineEnvironmentTest.groovy
  vars/piperPipelineStageInit.groovy
  vars/setupCommonPipelineEnvironment.groovy
Labels: REVIEW

#2258 Add commit to clone and pull
  cmd/abapEnvironmentCheckoutBranch.go
  cmd/abapEnvironmentCloneGitRepo.go
  cmd/abapEnvironmentCloneGitRepo_test.go
  cmd/abapEnvironmentPullGitRepo.go
  cmd/abapEnvironmentPullGitRepo_generated.go
  cmd/abapEnvironmentPullGitRepo_test.go
  cmd/abapEnvironmentRunATCCheck.go
  documentation/docs/steps/abapEnvironmentCheckoutBranch.md
  documentation/docs/steps/abapEnvironmentCloneGitRepo.md
  documentation/docs/steps/abapEnvironmentPullGitRepo.md
  pkg/abaputils/addonDescriptor.go
  pkg/abaputils/manageGitRepositoryUtils.go
  pkg/abaputils/manageGitRepositoryUtils_test.go
  resources/default_pipeline_environment.yml
  resources/metadata/abapEnvironmentPullGitRepo.yaml
Labels: ABAP, REVIEW

#2191 refactor: remove obsolete mandatory:false
  resources/metadata/checkmarx.yaml
  resources/metadata/detect.yaml
  resources/metadata/kaniko.yaml
  resources/metadata/kubernetesdeploy.yaml
  resources/metadata/versioning.yaml
  resources/metadata/xsDeploy.yaml
Labels: work in progress 🚧

#2296 feat(jenkins): add package for Jenkins interactions
  go.mod
  go.sum
  pkg/jenkins/artifact.go
  pkg/jenkins/build.go
  pkg/jenkins/build_test.go
  pkg/jenkins/jenkins.go
  pkg/jenkins/jenkins_test.go
  pkg/jenkins/mocks/Artifact.go
  pkg/jenkins/mocks/Build.go
  pkg/jenkins/mocks/Jenkins.go
  pkg/jenkins/mocks/Task.go
  pkg/jenkins/task.go
Labels: REVIEW

#2297 fortifyExecuteScan: fix quoting of default values for "src"
  cmd/fortifyExecuteScan_generated.go
  resources/metadata/fortify.yaml
Labels: REVIEW, documentation

#2004 Abap pipeline extension for cloneGitRepo & checkoutBranch to be used
  documentation/docs/pipelines/abapEnvironment/configuration.md
  documentation/docs/pipelines/abapEnvironment/introduction.md
  test/groovy/templates/AbapEnvironmentPipelineStageCloneRepositoriesTest.groovy
  test/groovy/templates/AbapEnvironmentPipelineStagePrepareSystemTest.groovy
  vars/abapEnvironmentPipelineStageCloneRepositories.groovy
Labels: ABAP

#2292 Install maven artifacts before running Detect
  cmd/detectExecuteScan.go
  cmd/detectExecuteScan_generated.go
  cmd/detectExecuteScan_test.go
  resources/metadata/detect.yaml
Labels: REVIEW

#2273 Add step abapEnvironmentCreateSystem
  cmd/abapEnvironmentCreateSystem.go
  cmd/abapEnvironmentCreateSystem_generated.go
  cmd/abapEnvironmentCreateSystem_generated_test.go
  cmd/abapEnvironmentCreateSystem_test.go
  cmd/piper.go
  pkg/mock/fileUtils.go
  pkg/piperutils/FileUtils.go
  resources/metadata/abapEnvironmentCreateSystem.yaml
Labels: REVIEW

#2302 Fix setupCPE bug
  test/groovy/SetupCommonPipelineEnvironmentTest.groovy
  vars/setupCommonPipelineEnvironment.groovy
Labels: bug :bug:

#2308 Add preDeploymentHook to multicloudDeploy step
  test/groovy/MulticloudDeployTest.groovy
  vars/multicloudDeploy.groovy
Labels: REVIEW

#2298 New step gatlingExecuteTests
  documentation/docs/steps/gatlingExecuteTests.md
  documentation/mkdocs.yml
  resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
  resources/default_pipeline_environment.yml
  test/groovy/GatlingExecuteTestsTest.groovy
  test/groovy/templates/PiperPipelineStagePerformanceTest.groovy
  vars/gatlingExecuteTests.groovy
  vars/piperPipelineStagePerformance.groovy
Labels: REVIEW, enhancement

#2247 feat(Gitops): Gitops update deployment with helm
  cmd/gitopsUpdateDeployment.go
  cmd/gitopsUpdateDeployment_generated.go
  cmd/gitopsUpdateDeployment_test.go
  pkg/git/git.go
  pkg/git/git_test.go
  resources/metadata/gitopsUpdateDeployment.yaml
Labels: REVIEW

#2206 feat(http): support empty passwords
  pkg/http/http.go
  pkg/http/http_test.go
Labels: Sonar

#2307 Add default stashes to metadata of cloudFoundryDeploy
  resources/metadata/cloudFoundryDeploy.yaml
Labels: REVIEW

#2312 npmExecuteScripts: allow passing a list of build descriptors to execute scripts for
  cmd/npmExecuteLint.go
  cmd/npmExecuteScripts.go
  cmd/npmExecuteScripts_generated.go
  cmd/npmExecuteScripts_test.go
  pkg/npm/npm.go
  pkg/npm/npm_test.go
  resources/metadata/npmExecuteScripts.yaml
Labels: REVIEW, go-piper

#2317 Hotfix ATC Check Variant
  cmd/abapEnvironmentRunATCCheck.go
  cmd/abapEnvironmentRunATCCheck_test.go
Labels: ABAP, REVIEW

#2320 change slack color to reflect all states
  resources/default_pipeline_environment.yml
  test/groovy/SlackSendNotificationTest.groovy
Labels: REVIEW

#2324 feat(http): expose tls insecure flag
  pkg/http/http.go
  pkg/http/http_test.go
Labels: REVIEW

#2315 whitesourcExecuteScan-go: Additional fixes
  cmd/whitesourceExecuteScan.go
  cmd/whitesourceExecuteScan_generated.go
  cmd/whitesourceExecuteScan_test.go
  pkg/whitesource/scan.go
  pkg/whitesource/scanNPM_test.go
  pkg/whitesource/scanPolling.go
  pkg/whitesource/scanPolling_test.go
  pkg/whitesource/scanUA.go
  pkg/whitesource/scanUA_test.go
  pkg/whitesource/scan_test.go
  pkg/whitesource/utilsMock.go
  resources/metadata/whitesource.yaml
Labels: REVIEW

#2332 Extend the legacy config check for "required" config keys
  resources/com.sap.piper/pipeline/cloudSdkToGppConfigSettings.yml
  test/groovy/CheckForLegacyConfigurationTest.groovy
  vars/checkForLegacyConfiguration.groovy
Labels: REVIEW

#2318 Refactor maven utils and add tests for install artifacts
  cmd/artifactPrepareVersion.go
  cmd/detectExecuteScan.go
  cmd/fortifyExecuteScan.go
  cmd/fortifyExecuteScan_test.go
  cmd/mavenBuild.go
  cmd/mavenBuild_test.go
  cmd/mavenExecute.go
  cmd/mavenExecuteIntegration.go
  cmd/mavenExecuteIntegration_test.go
  cmd/mavenExecuteStaticCodeChecks.go
  cmd/mavenExecuteStaticCodeChecks_test.go
  cmd/mavenExecute_test.go
  cmd/mtaBuild.go
  cmd/mtaBuild_test.go
  cmd/nexusUpload.go
  cmd/nexusUpload_test.go
  pkg/maven/maven.go
  pkg/maven/maven_test.go
  pkg/maven/settings.go
  pkg/maven/settings_test.go
  pkg/mock/fileUtils.go
  pkg/versioning/docker.go
  pkg/versioning/maven.go
  pkg/versioning/maven_test.go
  pkg/versioning/versioning.go
  pkg/whitesource/scanMaven.go
  pkg/whitesource/utils.go
Labels: REVIEW

#2349 Run nexusUpload in stage Promote
  cmd/nexusUpload.go
  cmd/nexusUpload_test.go
  resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
  resources/com.sap.piper/pipeline/stageDefaults.yml
  resources/metadata/nexusUpload.yaml
  test/groovy/templates/PiperPipelineStagePromoteTest.groovy
  vars/piperPipelineStagePromote.groovy
Labels: REVIEW

#2303 Create groovy step for abapEnvironmentCreateSystem
  cmd/abapEnvironmentCreateSystem_generated.go
  documentation/docs/pipelines/abapEnvironment/configuration.md
  documentation/docs/pipelines/abapEnvironment/introduction.md
  documentation/docs/scenarios/abapEnvironmentAddons.md
  documentation/docs/steps/abapEnvironmentCreateSystem.md
  documentation/mkdocs.yml
  resources/metadata/abapEnvironmentCreateSystem.yaml
  test/groovy/CommonStepsTest.groovy
  test/groovy/templates/AbapEnvironmentPipelineStageIntegrationTestsTest.groovy
  test/groovy/templates/AbapEnvironmentPipelineStagePrepareSystemTest.groovy
  vars/abapEnvironmentCreateSystem.groovy
  vars/abapEnvironmentPipelineStageCloneRepositories.groovy
  vars/abapEnvironmentPipelineStageIntegrationTests.groovy
  vars/abapEnvironmentPipelineStagePrepareSystem.groovy
Labels: REVIEW

#2352 Add mavenExecuteIntegration, mavenExecuteStaticCodeChecks, npmExecuteLint and npmExecuteScripts to piperPipelineStagePRVoting
  resources/com.sap.piper/pipeline/stageDefaults.yml
  test/groovy/templates/PiperPipelineStagePRVotingTest.groovy
  vars/piperPipelineStagePRVoting.groovy
Labels: REVIEW

#2357 Conditions for npmExecuteScripts in Additional Unit Tests
  resources/com.sap.piper/pipeline/stageDefaults.yml
Labels: REVIEW

#2359 remove duplicate function from interface
  cmd/mtaBuild.go
Labels: REVIEW

#2361 Add runStep conditions for mavenExecuteIntegration and npmExecuteScripts in Integration stage
  resources/com.sap.piper/pipeline/stageDefaults.yml
Labels: REVIEW

#2369 Update defaults for npmExecuteScripts and mavenExecuteIntegration to run install
  cmd/mavenExecuteIntegration_generated.go
  cmd/npmExecuteScripts_generated.go
  resources/metadata/mavenExecuteIntegration.yaml
  resources/metadata/npmExecuteScripts.yaml
Labels: REVIEW

#2371 chore(release): ignore stale issues
  .pipeline/config.yml
Labels: REVIEW

#2353 abapEnvironmentCreateSystem instead of Clone Repo
  documentation/docs/steps/abapEnvironmentCreateSystem.md
Labels: ABAP, REVIEW

#2351 install artifacts for Fortify
  cmd/fortifyExecuteScan.go
  cmd/fortifyExecuteScan_generated.go
  resources/metadata/fortify.yaml
Labels: REVIEW

#2358 chore(sonar): set proper error categories
  cmd/sonarExecuteScan.go
Labels: REVIEW

#1169 refactor(hadolint): implement step in GO
  cmd/hadolintExecute.go
  cmd/hadolintExecute_generated.go
  cmd/hadolintExecute_generated_test.go
  cmd/hadolintExecute_test.go
  cmd/piper.go
  pkg/hadolint/mocks/hadolintClient.go
  pkg/hadolint/mocks/hadolintPiperFileUtils.go
  resources/default_pipeline_environment.yml
  resources/metadata/hadolint.yaml
  test/groovy/HadolintExecuteTest.groovy
  vars/hadolintExecute.groovy
Labels: REVIEW, go-piper

#2360 Always use artifactPrepareVersion
  test/groovy/templates/PiperPipelineStageInitTest.groovy
  vars/piperPipelineStageInit.groovy
Labels: REVIEW

#2381 chore(code climate):sync config with local mdlint config
  .codeclimate.yml
Labels: Code Quality, REVIEW

#2383 fix: remove markdownlint findings for MD012
  .codeclimate.yml
  .markdownlint.yml
  README.md
  documentation/docs/extensibility.md
  documentation/docs/index.md
  documentation/docs/infrastructure/vault.md
  documentation/docs/scenarios/CAP_Scenario.md
  documentation/docs/stages/introduction.md
  documentation/docs/steps/abapEnvironmentCloneGitRepo.md
  documentation/docs/steps/abapEnvironmentCreateSystem.md
  documentation/docs/steps/fortifyExecuteScan.md
  documentation/docs/steps/mavenBuild.md
  documentation/docs/steps/npmExecuteScripts.md
Labels: Code Quality, REVIEW

#2378 chore(code climate): ignore generated mock files
  .codeclimate.yml
Labels: REVIEW

#2385 chore: fix markdownlint findings
  .codeclimate.yml
  .markdownlint.yml
  DEVELOPMENT.md
  documentation/architecture/decisions/nexusUpload.md
  documentation/docs/guidedtour.md
  documentation/docs/index.md
  documentation/docs/pipelines/cloud-sdk/build-tools.md
  documentation/docs/pipelines/cloud-sdk/cloud-qualities.md
  documentation/docs/pipelines/cloud-sdk/configuration.md
  documentation/docs/pipelines/cloud-sdk/introduction.md
  documentation/docs/scenarios/CAP_Scenario.md
  documentation/docs/scenarios/abapEnvironmentAddons.md
  documentation/docs/scenarios/changeManagement.md
  documentation/docs/scenarios/ui5-sap-cp/Readme.md
  documentation/docs/scenarios/upload-to-transportrequest/Readme.md
  documentation/docs/scenarios/xsa-deploy/Readme.md
  documentation/docs/stages/examples.md
  documentation/docs/stages/introduction.md
  documentation/docs/steps/neoDeploy.md
  documentation/docs/steps/uiVeri5ExecuteTests.md
Labels: Code Quality, REVIEW

#2380 Catch runtime error in ATC step
  cmd/abapEnvironmentRunATCCheck.go
Labels: ABAP, REVIEW

#2387 Stash also original jar
  resources/default_pipeline_environment.yml
Labels: REVIEW

#2389 Use devxci/mbtci:1.0.16.1
  resources/metadata/nexusUpload.yaml
Labels: REVIEW

#2365 Remove sdk docs
  documentation/docs/extensibility.md
  documentation/docs/guidedtour.md
  documentation/docs/index.md
  documentation/docs/infrastructure/overview.md
  documentation/docs/pipelines/cloud-sdk/build-tools.md
  documentation/docs/pipelines/cloud-sdk/cloud-qualities.md
  documentation/docs/pipelines/cloud-sdk/configuration.md
  documentation/docs/pipelines/cloud-sdk/introduction.md
  documentation/mkdocs.yml
Labels: REVIEW

#2392 remove excess logging in abapEnvironmentPullGitRepo step
  cmd/abapEnvironmentPullGitRepo.go
Labels: ABAP, REVIEW

#2402 Add scenario documentation for test setup
  documentation/docs/pipelines/abapEnvironment/configuration.md
  documentation/docs/pipelines/abapEnvironment/introduction.md
  documentation/docs/scenarios/abapEnvironmentTest.md
  documentation/mkdocs.yml
Labels: ABAP

#2403 Document default implementation of stages
  documentation/docs/stages/introduction.md
Labels: REVIEW

#2329 feat: expose complete step metadata through generated function
  cmd/abapAddonAssemblyKitCheckCVs_generated.go
  cmd/abapAddonAssemblyKitCheckPV_generated.go
  cmd/abapAddonAssemblyKitCreateTargetVector_generated.go
  cmd/abapAddonAssemblyKitPublishTargetVector_generated.go
  cmd/abapAddonAssemblyKitRegisterPackages_generated.go
  cmd/abapAddonAssemblyKitReleasePackages_generated.go
  cmd/abapAddonAssemblyKitReserveNextPackages_generated.go
  cmd/abapEnvironmentAssemblePackages_generated.go
  cmd/abapEnvironmentCheckoutBranch_generated.go
  cmd/abapEnvironmentCloneGitRepo_generated.go
  cmd/abapEnvironmentCreateSystem_generated.go
  cmd/abapEnvironmentPullGitRepo_generated.go
  cmd/abapEnvironmentRunATCCheck_generated.go
  cmd/artifactPrepareVersion_generated.go
  cmd/checkmarxExecuteScan_generated.go
  cmd/cloudFoundryCreateServiceKey_generated.go
  cmd/cloudFoundryCreateService_generated.go
  cmd/cloudFoundryCreateSpace_generated.go
  cmd/cloudFoundryDeleteService_generated.go
  cmd/cloudFoundryDeleteSpace_generated.go
  cmd/cloudFoundryDeploy_generated.go
  cmd/containerSaveImage_generated.go
  cmd/detectExecuteScan_generated.go
  cmd/fortifyExecuteScan_generated.go
  cmd/gctsCloneRepository_generated.go
  cmd/gctsCreateRepository_generated.go
  cmd/gctsDeploy_generated.go
  cmd/gctsExecuteABAPUnitTests_generated.go
  cmd/gctsRollback_generated.go
  cmd/githubCheckBranchProtection_generated.go
  cmd/githubCreatePullRequest_generated.go
  cmd/githubPublishRelease_generated.go
  cmd/githubSetCommitStatus_generated.go
  cmd/gitopsUpdateDeployment_generated.go
  cmd/hadolintExecute_generated.go
  cmd/jsonApplyPatch_generated.go
  cmd/kanikoExecute_generated.go
  cmd/karmaExecuteTests_generated.go
  cmd/kubernetesDeploy_generated.go
  cmd/malwareExecuteScan_generated.go
  cmd/mavenBuild_generated.go
  cmd/mavenExecuteIntegration_generated.go
  cmd/mavenExecuteStaticCodeChecks_generated.go
  cmd/mavenExecute_generated.go
  cmd/metadata_generated.go
  cmd/mtaBuild_generated.go
  cmd/nexusUpload_generated.go
  cmd/npmExecuteLint_generated.go
  cmd/npmExecuteScripts_generated.go
  cmd/protecodeExecuteScan_generated.go
  cmd/sonarExecuteScan_generated.go
  cmd/vaultRotateSecretId_generated.go
  cmd/whitesourceExecuteScan_generated.go
  cmd/xsDeploy_generated.go
  pkg/generator/helper/helper.go
  pkg/generator/helper/testdata/TestProcessMetaFiles/custom_step_code_generated.golden
  pkg/generator/helper/testdata/TestProcessMetaFiles/step_code_generated.golden
  resources/metadata/fortify.yaml
Labels: REVIEW

#2232 generator helper: support for map[string]interface{}
  pkg/generator/helper/helper.go
Labels: REVIEW, discussion

#2413 Build and Publish Add-on Products on SAP Cloud Platform ABAP Environment: Change troubleshooting links
  documentation/docs/scenarios/abapEnvironmentAddons.md
Labels: ABAP, REVIEW

#2398 refactor(checks): use warnings-ng plugin
  documentation/docs/images/StaticChecks_Threshold.png
  documentation/docs/steps/checksPublishResults.md
  resources/default_pipeline_environment.yml
  test/groovy/ChecksPublishResultsTest.groovy
  vars/checksPublishResults.groovy
Labels: REVIEW

#2426 chore(jenkins): expose artifacts save method
  pkg/jenkins/artifact.go
  pkg/jenkins/build_test.go
  pkg/jenkins/mocks/Artifact.go
Labels: REVIEW

#2401 WhiteSource: Force update of project when "checkPolicies" failed
  pkg/npm/npm.go
  pkg/piperutils/FileUtils.go
  pkg/piperutils/fileUtils_test.go
  pkg/whitesource/scanNPM.go
  pkg/whitesource/scanNPM_test.go
  pkg/whitesource/utilsMock.go
Labels: REVIEW, bug :bug:

#2431 Fix workingDir for mta whitesource scan
  cmd/whitesourceExecuteScan_generated.go
  resources/metadata/whitesource.yaml
Labels: REVIEW

#2433 fix(docs): typo in sample parameter
  documentation/docs/steps/checksPublishResults.md
Labels: REVIEW, documentation
