Repository SAP/jenkins-library, pull requests merged in 2020-04, with the labels that each got.

#1352 Fix test by resetting application context after each test
  test/groovy/util/BasePiperTest.groovy
Labels: REVIEW

#1355 Piper-Go: Allow aliases also for inputs of type "secret"
  cmd/getConfig.go
  cmd/piper.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/stepmeta.go
Labels: REVIEW

#1356 Generate documentation for nexusUpload Groovy part
  documentation/docs/steps/nexusUpload.md
  documentation/mkdocs.yml
Labels: REVIEW

#1359 Allow to trigger release manually
  .github/workflows/release-go.yml
  .github/workflows/upload-go-master.yml
  DEVELOPMENT.md
  contrib/perform-release.sh
Labels: REVIEW

#1343 Add step to prepare the version for an artifact
  .gitignore
  cmd/artifactPrepareVersion.go
  cmd/artifactPrepareVersion_generated.go
  cmd/artifactPrepareVersion_generated_test.go
  cmd/artifactPrepareVersion_test.go
  cmd/piper.go
  go.mod
  go.sum
  pkg/versioning/maven.go
  pkg/versioning/maven_test.go
  pkg/versioning/npm.go
  pkg/versioning/npm_test.go
  pkg/versioning/versioning.go
  pkg/versioning/versioning_test.go
  resources/metadata/versioning.yaml
  test/groovy/CommonStepsTest.groovy
  test/groovy/PiperExecuteBinTest.groovy
  vars/artifactPrepareVersion.groovy
  vars/piperExecuteBin.groovy
Labels: REVIEW, go-piper

#1332 Use stable version for setting maven version
  src/com/sap/piper/versioning/MavenArtifactVersioning.groovy
  test/groovy/ArtifactSetVersionTest.groovy
  test/groovy/com/sap/piper/versioning/MavenArtifactVersioningTest.groovy
Labels: REVIEW

#1348 Relax requirements for maven projects in nexus upload
  cmd/nexusUpload.go
  cmd/nexusUpload_generated.go
  cmd/nexusUpload_test.go
  integration/integration_nexus_upload_test.go
  integration/testdata/TestNexusIntegration/maven/pom.xml
  integration/testdata/TestNexusIntegration/maven/srv/pom.xml
  integration/testdata/TestNexusIntegration/maven/srv/target/my-app-1.0-classes.jar
  integration/testdata/TestNexusIntegration/maven/srv/target/my-app-1.0-javadoc.jar
  integration/testdata/TestNexusIntegration/maven/srv/target/my-app-1.0.jar
  pkg/piperutils/FileUtils.go
  resources/metadata/nexusUpload.yaml
Labels: REVIEW, go-piper

#1364 nexusUpload: Remove config processing from Groovy layer
  test/groovy/CommonStepsTest.groovy
  vars/nexusUpload.groovy
  vars/piperPipelineStageArtifactDeployment.groovy
Labels: REVIEW

#1289 fix: fixing issues with cf docker deployment
  test/groovy/CloudFoundryDeployTest.groovy
  vars/cloudFoundryDeploy.groovy
Labels: REVIEW

#1374 artifactPrepareVersion: new versioning option
  cmd/artifactPrepareVersion.go
  cmd/artifactPrepareVersion_generated.go
  cmd/artifactPrepareVersion_test.go
  resources/metadata/versioning.yaml
Labels: go-piper

#1368 Trigger integration test with command
  .github/workflows/integration-tests.yaml
Labels: REVIEW

#1376 Allow MEMBERs to trigger integration tests
  .github/workflows/integration-tests.yaml
Labels: REVIEW

#1320 refactor(sonar): switch to Sonar scan in GO
  cmd/protecodeExecuteScan.go
  cmd/sonarExecuteScan.go
  cmd/sonarExecuteScan_generated.go
  cmd/sonarExecuteScan_test.go
  pkg/piperutils/slices.go
  pkg/piperutils/slices_test.go
  resources/default_pipeline_environment.yml
  resources/metadata/sonar.yaml
  test/groovy/CommonStepsTest.groovy
  test/groovy/SonarExecuteScanTest.groovy
  vars/sonarExecuteScan.groovy
Labels: REVIEW, go-piper

#1361 Inherit from Kubernetes pod template
  test/groovy/DockerExecuteOnKubernetesTest.groovy
  vars/dockerExecuteOnKubernetes.groovy
Labels: REVIEW

#1379 Extend nexusUpload to also handle npm
  cmd/nexusUpload.go
  cmd/nexusUpload_generated.go
  cmd/nexusUpload_test.go
  integration/integration_nexus_upload_test.go
  integration/testdata/TestNexusIntegration/npm/package.json
  pkg/nexus/nexus.go
  pkg/nexus/nexus_test.go
  resources/metadata/nexusUpload.yaml
Labels: REVIEW

#1393 Automate go dependency updates
  .github/workflows/update-go-dependencies.yaml
  .pipeline/config.yml
Labels: REVIEW

#1400 fix: read config.yaml in getConfig command
  cmd/getConfig.go
Labels: REVIEW, go-piper

#1367 artifactPrepareVersioning: support more buildTools
  cmd/artifactPrepareVersion.go
  cmd/artifactPrepareVersion_generated.go
  cmd/artifactPrepareVersion_test.go
  go.mod
  go.sum
  pkg/versioning/docker.go
  pkg/versioning/docker_test.go
  pkg/versioning/inifile.go
  pkg/versioning/inifile_test.go
  pkg/versioning/jsonfile.go
  pkg/versioning/jsonfile_test.go
  pkg/versioning/maven.go
  pkg/versioning/maven_test.go
  pkg/versioning/npm.go
  pkg/versioning/npm_test.go
  pkg/versioning/versionfile.go
  pkg/versioning/versionfile_test.go
  pkg/versioning/versioning.go
  pkg/versioning/versioning_test.go
  pkg/versioning/yamlfile.go
  pkg/versioning/yamlfile_test.go
  resources/metadata/versioning.yaml
Labels: REVIEW, go-piper

#1382 Mask secrets
  cmd/abapEnvironmentPullGitRepo_generated.go
  cmd/artifactPrepareVersion_generated.go
  cmd/checkmarxExecuteScan_generated.go
  cmd/cloudFoundryCreateServiceKey_generated.go
  cmd/cloudFoundryDeleteService_generated.go
  cmd/detectExecuteScan_generated.go
  cmd/githubCreatePullRequest_generated.go
  cmd/githubPublishRelease_generated.go
  cmd/karmaExecuteTests_generated.go
  cmd/kubernetesDeploy_generated.go
  cmd/mavenBuild_generated.go
  cmd/mavenExecuteStaticCodeChecks_generated.go
  cmd/mavenExecute_generated.go
  cmd/mtaBuild_generated.go
  cmd/nexusUpload_generated.go
  cmd/protecodeExecuteScan_generated.go
  cmd/sonarExecuteScan_generated.go
  cmd/version_generated.go
  cmd/xsDeploy_generated.go
  pkg/config/stepmeta.go
  pkg/generator/helper/helper.go
  pkg/generator/helper/helper_test.go
  pkg/generator/helper/testdata/TestProcessMetaFiles/custom_step_code_generated.golden
  pkg/generator/helper/testdata/TestProcessMetaFiles/step_code_generated.golden
  pkg/log/log.go
  pkg/log/log_test.go
  resources/metadata/abapEnvironmentPullGitRepo.yaml
  resources/metadata/checkmarx.yaml
  resources/metadata/cloudFoundryCreateServiceKey.yaml
  resources/metadata/cloudFoundryDeleteService.yaml
  resources/metadata/detect.yaml
  resources/metadata/githubcreatepr.yaml
  resources/metadata/githubrelease.yaml
  resources/metadata/kubernetesdeploy.yaml
  resources/metadata/nexusUpload.yaml
  resources/metadata/protecode.yaml
  resources/metadata/sonar.yaml
  resources/metadata/versioning.yaml
  resources/metadata/xsDeploy.yaml
Labels: REVIEW

#1412 Configure default jenkins agent for kubernetes
  resources/default_pipeline_environment.yml
Labels: REVIEW

#1413 Use specific token for automated go dependency update PR
  .github/workflows/update-go-dependencies.yaml
Labels: REVIEW

#1408 Convert invalid config value types
  cmd/piper.go
  cmd/piper_test.go
Labels: REVIEW, go-piper

#1414 Add option to always run stages in a pod
  src/com/sap/piper/DebugReport.groovy
  test/groovy/DockerExecuteOnKubernetesTest.groovy
  test/groovy/PiperStageWrapperTest.groovy
  test/groovy/com/sap/piper/DebugReportTest.groovy
  vars/dockerExecuteOnKubernetes.groovy
  vars/piperStageWrapper.groovy
Labels: REVIEW

#1386 chore(actions): add workflow to generate docs
  .github/workflows/documentation.yaml
  .travis.yml
  documentation/bin/createDocu.sh
Labels: REVIEW

#1419 chore: cache .m2 directory during groovy tests
  .github/workflows/documentation.yaml
  .github/workflows/verify-groovy.yml
Labels: REVIEW

#1425 fix: improve stepResults handling
  pkg/piperenv/environment.go
  pkg/piperutils/stepResults.go
  pkg/piperutils/stepResults_test.go
Labels: REVIEW

#1423 Update Go dependencies
  go.mod
  go.sum
Labels: REVIEW, go-piper

#1390 feat(sonar): extract sonar project link to report JSON
  cmd/sonarExecuteScan.go
  cmd/sonarExecuteScan_test.go
  go.mod
  go.sum
  pkg/sonar/sonar.go
  pkg/sonar/sonar_test.go
  pkg/sonar/testData/invalid/.scannerwork/report-task.txt
  pkg/sonar/testData/valid/.scannerwork/report-task.txt
Labels: REVIEW

#1436 fix(sonar): do not fail on missing task report file
  cmd/sonarExecuteScan.go
Labels: REVIEW

#1300 Log command which is executed
  pkg/command/command.go
Labels: REVIEW

#1392 Document new identifier
  documentation/docs/scenarios/CAP_Scenario.md
  documentation/docs/scenarios/changeManagement.md
Labels: REVIEW

#1420 Fix documentation generation for cloud foundry
  vars/cloudFoundryDeploy.groovy
Labels: REVIEW

#1440 Fix integration tests on master
  .github/workflows/integration-tests.yaml
  consumer-test/consumerTestController.groovy
Labels: REVIEW

#1439 Document mavenBuild
  documentation/docs/steps/mavenBuild.md
Labels: REVIEW

#1329 Provide tooling for malware scanning
  cmd/malwareExecuteScan.go
  cmd/malwareExecuteScan_generated.go
  cmd/malwareExecuteScan_generated_test.go
  cmd/malwareExecuteScan_test.go
  cmd/piper.go
  resources/metadata/malwareExecuteScan.yaml
Labels: go-piper

#1444 fix(telemetry): correct source URL for web reporting
  .github/workflows/upload-go-master.yml
Labels: REVIEW

#1438 Add basic support for Helm 3 in kubernetesDeploy step
  cmd/kubernetesDeploy.go
  cmd/kubernetesDeploy_test.go
  documentation/docs/steps/kubernetesDeploy.md
  documentation/mkdocs.yml
  resources/metadata/kubernetesdeploy.yaml
Labels: REVIEW

#1388 Maven execute go
  .gitignore
  cmd/detectExecuteScan.go
  cmd/mavenExecute.go
  cmd/mavenExecuteStaticCodeChecks_test.go
  cmd/mavenExecute_test.go
  cmd/nexusUpload_test.go
  pkg/maven/maven.go
  pkg/maven/maven_test.go
  pkg/maven/settings.go
  pkg/piperutils/slices.go
  pkg/piperutils/slices_test.go
  test/groovy/ArtifactSetVersionTest.groovy
  test/groovy/CommonStepsTest.groovy
  test/groovy/MavenExecuteTest.groovy
  test/groovy/NexusUploadTest.groovy
  test/groovy/com/sap/piper/versioning/MavenArtifactVersioningTest.groovy
  test/groovy/util/JenkinsFileExistsRule.groovy
  test/groovy/util/JenkinsMavenExecuteRule.groovy
  vars/checkmarxExecuteScan.groovy
  vars/kubernetesDeploy.groovy
  vars/mavenBuild.groovy
  vars/mavenExecute.groovy
  vars/nexusUpload.groovy
  vars/piperExecuteBin.groovy
Labels: REVIEW, go-piper

#1450 docs: omit <nil> in parameter table
  pkg/generator/helper/docuHelper.go
  pkg/generator/helper/docuHelper_test.go
Labels: REVIEW

#1453 docs: show possible values in step documentation
  pkg/config/stepmeta.go
  pkg/generator/helper/docuHelper.go
  pkg/generator/helper/docuHelper_test.go
Labels: REVIEW

#1422 Implement JavaScript backend build step
  cmd/npmExecuteScripts.go
  cmd/npmExecuteScripts_generated.go
  cmd/npmExecuteScripts_generated_test.go
  cmd/npmExecuteScripts_test.go
  cmd/piper.go
  integration/integration_npmExecuteScripts_test.go
  integration/testdata/TestNpmIntegration/.npmrc
  integration/testdata/TestNpmIntegration/package-lock.json
  integration/testdata/TestNpmIntegration/package.json
  resources/metadata/npmExecuteScripts.yaml
  src/com/sap/piper/DownloadCacheUtils.groovy
  test/groovy/CommonStepsTest.groovy
  vars/npmExecuteScripts.groovy
Labels: REVIEW, go-piper

#1447 Elaborate on best practices when writing go steps. (Proposal)
  DEVELOPMENT.md
Labels: REVIEW, documentation, go-piper

#1457 artifactPrepareVersion: define versioning scheme
  cmd/artifactPrepareVersion.go
  cmd/artifactPrepareVersion_generated.go
  pkg/versioning/inifile.go
  pkg/versioning/versioning.go
  pkg/versioning/versioning_test.go
  resources/metadata/versioning.yaml
Labels: go-piper

#1459 docs: remove dangling whitespaces
  pkg/generator/helper/docuHelper.go
  pkg/generator/helper/docuHelper_test.go
Labels: REVIEW

#1455 Enable the use of artifactPrepareVersion instead of artifactSetVersion
  cmd/artifactPrepareVersion_generated.go
  resources/metadata/versioning.yaml
  vars/artifactPrepareVersion.groovy
Labels: REVIEW, go-piper

#1433 Fixing Link to tmsUpload Step
  documentation/docs/scenarios/TMS_Extension.md
Labels: documentation

#1336 adapt UI5 scenario docu
  documentation/docs/scenarios/ui5-sap-cp/Readme.md
  documentation/docs/scenarios/ui5-sap-cp/files/mta.yaml
Labels: documentation

#1458 docs: add possible values
  resources/metadata/checkmarx.yaml
  resources/metadata/detect.yaml
  resources/metadata/gctsCreateRepository.yaml
  resources/metadata/mtaBuild.yaml
  resources/metadata/protecode.yaml
  resources/metadata/sonar.yaml
  resources/metadata/versioning.yaml
  resources/metadata/xsDeploy.yaml
Labels: REVIEW

#1462 Set piper exe version when under test
  src/com/sap/piper/PiperGoUtils.groovy
Labels: REVIEW

#1443 Pass golang error details to Jenkins pipeline
  .gitignore
  cmd/abapEnvironmentPullGitRepo_generated.go
  cmd/artifactPrepareVersion_generated.go
  cmd/checkmarxExecuteScan_generated.go
  cmd/cloudFoundryCreateServiceKey_generated.go
  cmd/cloudFoundryDeleteService_generated.go
  cmd/detectExecuteScan_generated.go
  cmd/gctsCreateRepository_generated.go
  cmd/githubCreatePullRequest_generated.go
  cmd/githubPublishRelease_generated.go
  cmd/karmaExecuteTests_generated.go
  cmd/kubernetesDeploy_generated.go
  cmd/malwareExecuteScan_generated.go
  cmd/mavenBuild_generated.go
  cmd/mavenExecuteStaticCodeChecks_generated.go
  cmd/mavenExecute_generated.go
  cmd/mtaBuild_generated.go
  cmd/nexusUpload_generated.go
  cmd/npmExecuteScripts_generated.go
  cmd/piper.go
  cmd/protecodeExecuteScan_generated.go
  cmd/sonarExecuteScan_generated.go
  cmd/version_generated.go
  cmd/xsDeploy_generated.go
  pkg/generator/helper/helper.go
  pkg/generator/helper/testdata/TestProcessMetaFiles/custom_step_code_generated.golden
  pkg/generator/helper/testdata/TestProcessMetaFiles/step_code_generated.golden
  pkg/log/fatalHook.go
  pkg/log/fatalHook_test.go
  pkg/log/log.go
  test/groovy/PiperExecuteBinTest.groovy
  vars/piperExecuteBin.groovy
Labels: REVIEW, go-piper

#1448 Bootstrap documentation for Piper-NG CLI/GH Action
  documentation/docs/cli/index.md
  documentation/docs/index.md
  documentation/mkdocs.yml
Labels: REVIEW, documentation

#1479 Dont dedup mvn flags
  cmd/mavenExecute.go
  pkg/piperutils/slices.go
  pkg/piperutils/slices_test.go
Labels: REVIEW, bug :bug:

#1467 HTTP pkg: refine TransportTimeout
  pkg/http/http.go
Labels: REVIEW, go-piper

#1481 fix(sonar): remove .sonar-scanner and .certificates folder after scan
  vars/sonarExecuteScan.groovy
Labels: REVIEW

#1471 docs: add general config parameters to GO docs
  pkg/generator/helper/docuHelper.go
  pkg/generator/helper/docuHelper_test.go
Labels: REVIEW

#1486 docs: add possible value for bool parameters
  pkg/generator/helper/docuHelper.go
  pkg/generator/helper/docuHelper_test.go
Labels: REVIEW, documentation
