Repository SAP/jenkins-library, pull requests merged in 2020-03, with the labels that each got.

#1237 Add GetTestModulesExcludes to pkg/maven
  pkg/maven/maven.go
  pkg/maven/maven_test.go
  test/resources/maven/integration-tests/pom.xml
  test/resources/maven/pom.xml
  test/resources/maven/unit-tests/pom.xml
Labels: REVIEW, go-piper

#1235 Get rid of two dimensional env array
  cmd/kubernetesDeploy_test.go
  pkg/mock/runner.go
Labels: REVIEW, go-piper

#1233 Eliminte envExecRunner
  cmd/interfaces.go
  cmd/kubernetesDeploy.go
  cmd/mtaBuild.go
  pkg/mock/runner.go
Labels: REVIEW, go-piper

#1234 Have strategy for environment variable handling only once
  pkg/command/command.go
  pkg/command/command_test.go
Labels: REVIEW, go-piper

#1240 Build piper binary in Consumer Tests
  consumer-test/TestRunnerThread.groovy
  src/com/sap/piper/PiperGoUtils.groovy
Labels: MERGE, REVIEW

#1250 Implementation of Nexus upload as Go package
  pkg/nexus/nexus.go
  pkg/nexus/nexus_test.go
Labels: REVIEW, go-piper

#1251 Add Maven static code checks
  cmd/mavenStaticCodeChecks.go
  cmd/mavenStaticCodeChecks_generated.go
  cmd/mavenStaticCodeChecks_generated_test.go
  cmd/mavenStaticCodeChecks_test.go
  cmd/piper.go
  resources/metadata/mavenStaticCodeChecks.yaml
Labels: REVIEW, go-piper

#1258 Fix typo in mavenStaticCodeChecks.yaml
  cmd/mavenStaticCodeChecks_generated.go
  resources/metadata/mavenStaticCodeChecks.yaml
Labels: REVIEW

#1261 Add groovy wrapper for mavenExecuteStaticCodeChecks and rename go step
  cmd/mavenExecuteStaticCodeChecks.go
  cmd/mavenExecuteStaticCodeChecks_generated.go
  cmd/mavenExecuteStaticCodeChecks_generated_test.go
  cmd/mavenExecuteStaticCodeChecks_test.go
  cmd/mavenStaticCodeChecks_generated_test.go
  cmd/piper.go
  resources/metadata/mavenStaticCodeChecks.yaml
  test/groovy/CommonStepsTest.groovy
  test/groovy/MavenExecuteStaticCodeChecksTest.groovy
  vars/mavenExecuteStaticCodeChecks.groovy
Labels: REVIEW

#1245 Maven build/install step
  cmd/mavenBuild.go
  cmd/mavenBuild_generated.go
  cmd/mavenBuild_generated_test.go
  cmd/mavenBuild_test.go
  cmd/piper.go
  resources/metadata/mavenBuild.yaml
  resources/metadata/mavenExecute.yaml
Labels: REVIEW, go-piper

#1268 Add Evaluate() method to maven package
  pkg/maven/maven.go
  pkg/maven/maven_test.go
Labels: REVIEW, go-piper

#1298 Add DownloadCacheUtils for handling download cache docker container
  resources/com.sap.piper/templates/mvn_download_cache_proxy_settings.xml
  src/com/sap/piper/DownloadCacheUtils.groovy
  test/groovy/DownloadCacheUtilsTest.groovy
Labels: REVIEW

#1255 Implement nexusUpload command and tests
  cmd/nexusUpload.go
  cmd/nexusUpload_generated.go
  cmd/nexusUpload_generated_test.go
  cmd/nexusUpload_test.go
  cmd/piper.go
  documentation/architecture/decisions/nexusUpload.md
  go.mod
  go.sum
  integration/integration_nexus_upload_test.go
  integration/testdata/TestNexusIntegration/maven/pom.xml
  integration/testdata/TestNexusIntegration/maven/target/my-app-1.0.jar
  integration/testdata/TestNexusIntegration/mta/.pipeline/commonPipelineEnvironment/mtarFilePath
  integration/testdata/TestNexusIntegration/mta/mta.yaml
  integration/testdata/TestNexusIntegration/mta/test.mtar
  pkg/nexus/nexus.go
  pkg/nexus/nexus_test.go
  resources/metadata/nexusUpload.yaml
  test/groovy/CommonStepsTest.groovy
  test/groovy/NexusUploadTest.groovy
  vars/commonPipelineEnvironment.groovy
  vars/nexusUpload.groovy
  vars/piperExecuteBin.groovy
Labels: REVIEW, go-piper

#1291 Add ReportAggregator to collect information about executed stages and create reports
  resources/com.sap.piper/templates/pipeline_report.txt
  src/com/sap/piper/QualityCheck.groovy
  src/com/sap/piper/QualityCheckCategory.groovy
  src/com/sap/piper/ReportAggregator.groovy
Labels: REVIEW

#1042 refactor(sonar): implement Sonar step in GO
  cmd/piper.go
  cmd/sonarExecuteScan.go
  cmd/sonarExecuteScan_generated.go
  cmd/sonarExecuteScan_generated_test.go
  cmd/sonarExecuteScan_test.go
  go.sum
  pkg/generator/helper/helper.go
  pkg/piperutils/FileUtils.go
  pkg/piperutils/slices.go
  pkg/piperutils/slices_test.go
  resources/metadata/sonar.yaml
Labels: go-piper

#1317 Always pull sidecar images by default
  resources/default_pipeline_environment.yml
Labels: REVIEW

#1276 Add tests for maven build
  cmd/mavenBuild.go
  cmd/mavenBuild_test.go
  pkg/mock/fileUtils.go
Labels: REVIEW

#1308 Add static code checks stage
  cmd/mavenExecuteStaticCodeChecks.go
  cmd/mavenExecuteStaticCodeChecks_generated.go
  cmd/mavenExecuteStaticCodeChecks_test.go
  cmd/sonarExecuteScan.go
  resources/metadata/mavenStaticCodeChecks.yaml
  test/groovy/MavenExecuteStaticCodeChecksTest.groovy
  vars/mavenExecuteStaticCodeChecks.groovy
  vars/piperPipelineStageMavenStaticCodeChecks.groovy
Labels: REVIEW

#1346 Pass custom config and default configs also to getConfig
  vars/piperExecuteBin.groovy
Labels: REVIEW

#1324 Migrate stage artifact deployment from Cloud SDK Pipeline-Lib
  cmd/nexusUpload.go
  cmd/nexusUpload_generated.go
  cmd/nexusUpload_test.go
  pkg/nexus/nexus.go
  pkg/nexus/nexus_test.go
  resources/metadata/nexusUpload.yaml
  test/groovy/CommonStepsTest.groovy
  vars/nexusUpload.groovy
  vars/piperExecuteBin.groovy
  vars/piperPipelineStageArtifactDeployment.groovy
Labels: REVIEW
