Repository SAP/jenkins-library, pull requests merged in 2020-07, with the labels that each got.

#1734 Remove defaults for mtaBuild
  resources/default_pipeline_environment.yml
Labels: REVIEW

#1738 More accurate tests for cf login check and cf login
  pkg/cloudfoundry/Authentication.go
  pkg/cloudfoundry/CloudFoundry_test.go
Labels: REVIEW

#1742 Add isolation for CF Deployments in multicloudDeploy step
  test/groovy/MulticloudDeployTest.groovy
  vars/multicloudDeploy.groovy
Labels: REVIEW

#1747 Separate log folders for neo deployments
  test/groovy/NeoDeployTest.groovy
  vars/neoDeploy.groovy
Labels: REVIEW

#1736 Cf create services in multiclouddeploy step
  src/com/sap/piper/ConfigurationHelper.groovy
  test/groovy/MulticloudDeployTest.groovy
  test/groovy/com/sap/piper/ConfigurationHelperTest.groovy
  vars/multicloudDeploy.groovy
Labels: REVIEW

#1749 Fix stashing issue with binrary execution
  pkg/config/stepmeta.go
  pkg/config/stepmeta_test.go
  test/groovy/PiperExecuteBinTest.groovy
  vars/piperExecuteBin.groovy
Labels: REVIEW

#1740 Add documentation to scale the infrastructure with Kubernetes or Jenkins agents
  documentation/docs/guidedtour.md
  documentation/docs/images/agent.png
  documentation/docs/images/env.png
  documentation/docs/infrastructure/customjenkins.md
  documentation/docs/infrastructure/overview.md
  documentation/mkdocs.yml
Labels: REVIEW, documentation

#1756 Update Go dependencies
  go.mod
  go.sum
Labels: REVIEW, go-piper

#1761 Add mta extension credentials handling to cloudFoundryDeploy step
  resources/default_pipeline_environment.yml
  test/groovy/CloudFoundryDeployTest.groovy
  test/groovy/MulticloudDeployTest.groovy
  vars/cloudFoundryDeploy.groovy
  vars/multicloudDeploy.groovy
Labels: REVIEW

#1753 Improve documentation for the ABAP Environment Pipeline
  documentation/docs/images/abapPipelineOverview.png
  documentation/docs/pipelines/abapEnvironment/configuration.md
  documentation/docs/pipelines/abapEnvironment/introduction.md
  documentation/mkdocs.yml
Labels: REVIEW, documentation

#1769 Fix containers map and add test
  src/com/sap/piper/k8s/ContainerMap.groovy
  test/groovy/com/sap/piper/k8s/ContainerMapTest.groovy
  test/groovy/util/JenkinsPiperExecuteBinRule.groovy
Labels: REVIEW

#1697 TMS_Extension.md changed
  documentation/docs/scenarios/TMS_Extension.md
Labels: REVIEW

#1752 Host parameter fix
  cmd/abapEnvironmentPullGitRepo.go
  cmd/abapEnvironmentPullGitRepo_generated.go
  cmd/abapEnvironmentPullGitRepo_test.go
  cmd/abapEnvironmentRunATCCheck.go
  cmd/abapEnvironmentRunATCCheck_generated.go
  cmd/abapEnvironmentRunATCCheck_test.go
  documentation/docs/steps/abapEnvironmentRunATCCheck.md
  resources/metadata/abapEnvironmentPullGitRepo.yaml
  resources/metadata/abapEnvironmentRunATCCheck.yaml
Labels: ABAP

#1778 Make aliasing more resilient
  pkg/config/config.go
  pkg/config/config_test.go
Labels: REVIEW, go-piper

#1780 NpmExecuteScripts add script options
  cmd/npmExecuteLint.go
  cmd/npmExecuteScripts.go
  cmd/npmExecuteScripts_generated.go
  cmd/npmExecuteScripts_test.go
  integration/integration_npm_execute_scripts_test.go
  integration/testdata/TestNpmIntegration/runScriptsWithOptions/main.js
  integration/testdata/TestNpmIntegration/runScriptsWithOptions/package-lock.json
  integration/testdata/TestNpmIntegration/runScriptsWithOptions/package.json
  pkg/npm/npm.go
  pkg/npm/npm_test.go
  resources/metadata/npmExecuteScripts.yaml
Labels: REVIEW, go-piper

#1765 kanikoExecute - golang version
  cmd/kanikoExecute.go
  cmd/kanikoExecute_generated.go
  cmd/kanikoExecute_generated_test.go
  cmd/kanikoExecute_test.go
  cmd/piper.go
  resources/default_pipeline_environment.yml
  resources/metadata/kaniko.yaml
  test/groovy/CommonStepsTest.groovy
  test/groovy/KanikoExecuteTest.groovy
  vars/kanikoExecute.groovy
Labels: REVIEW, go-piper

#1786 Add step for end to end test execution
  documentation/docs/steps/npmExecuteEndToEndTests.md
  documentation/mkdocs.yml
  test/groovy/CommonStepsTest.groovy
  test/groovy/NpmExecuteEndToEndTestsTest.groovy
  vars/multicloudDeploy.groovy
  vars/npmExecuteEndToEndTests.groovy
  vars/runClosures.groovy
Labels: REVIEW

#1791 Add report handling to npmExecuteEndToEndTests
  resources/default_pipeline_environment.yml
  test/groovy/NpmExecuteEndToEndTestsTest.groovy
  test/groovy/TestsPublishResultsTest.groovy
  vars/npmExecuteEndToEndTests.groovy
  vars/testsPublishResults.groovy
Labels: REVIEW, enhancement

#1717 file mock: Dont store content of written or deleted file
  pkg/mock/fileUtils.go
Labels: REVIEW

#1721 Introduce stat command into Files utils and correspoding mock
  pkg/mock/fileUtils.go
  pkg/mock/fileUtils_test.go
  pkg/piperutils/FileUtils.go
Labels: REVIEW

#1802 Apply alias to secrets
  pkg/config/config.go
  pkg/config/config_test.go
Labels: REVIEW

#1781 Revamp documentation generation for golang steps
  cmd/detectExecuteScan_generated.go
  cmd/whitesourceExecuteScan_generated.go
  documentation/docs/steps/artifactPrepareVersion.md
  documentation/docs/steps/detectExecuteScan.md
  pkg/config/stepmeta.go
  pkg/config/stepmeta_test.go
  pkg/generator/helper/docuHelper.go
  pkg/generator/helper/docuHelper_test.go
  pkg/generator/helper/goUtils.go
  pkg/generator/helper/piper-context-defaults.yaml
  resources/metadata/detect.yaml
  resources/metadata/whitesource.yaml
Labels: documentation

#1810 Fix typo: articale -> article
  documentation/docs/steps/kanikoExecute.md
Labels: REVIEW

#1800 Add buildDescriptorExcludeList parameter to npmExecuteScripts step
  cmd/npmExecuteLint.go
  cmd/npmExecuteScripts.go
  cmd/npmExecuteScripts_generated.go
  cmd/npmExecuteScripts_test.go
  pkg/npm/npm.go
  pkg/npm/npm_test.go
  resources/metadata/npmExecuteScripts.yaml
  test/groovy/NpmExecuteEndToEndTestsTest.groovy
  vars/npmExecuteEndToEndTests.groovy
Labels: REVIEW

#1796 Pass stageName through to steps
  vars/piperPipelineStageAcceptance.groovy
  vars/piperPipelineStageBuild.groovy
  vars/piperPipelineStageIntegration.groovy
  vars/piperPipelineStageRelease.groovy
Labels: REVIEW

#1813 Use npmExecuteEndToEndTests step in Release/Acceptance stage if it is configured
  resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
  resources/com.sap.piper/pipeline/stageDefaults.yml
  test/groovy/NpmExecuteEndToEndTestsTest.groovy
  test/groovy/templates/PiperPipelineStageAcceptanceTest.groovy
  test/groovy/templates/PiperPipelineStageReleaseTest.groovy
  vars/npmExecuteEndToEndTests.groovy
  vars/piperPipelineStageAcceptance.groovy
  vars/piperPipelineStageRelease.groovy
Labels: REVIEW

#1817 Fix error in documentation
  documentation/docs/pipelines/abapEnvironment/configuration.md
Labels: REVIEW

#1814 Change query parameter delimiter to '&'
  src/com/sap/piper/integration/CloudFoundry.groovy
Labels: REVIEW

#1767 checkmarxExecuteScan: added resourceRef for secrets in step yaml
  cmd/checkmarxExecuteScan_generated.go
  resources/metadata/checkmarx.yaml
Labels: REVIEW

#1819 Rewrite mta IT using docker cli
  integration/docker_integration_test_executor.go
  integration/integration_mta_build_test.go
  integration/piper-command-wrapper.sh
Labels: REVIEW

#1820 Maven Build Integration Test
  integration/docker_integration_test_executor.go
  integration/integration_maven_build_test.go
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/.gitignore
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/.pipeline/config.yml
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/application/pom.xml
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/application/src/main/java/mydemo/Application.java
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/application/src/main/java/mydemo/SecurityConfig.java
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/application/src/main/java/mydemo/controllers/HelloWorldController.java
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/application/src/main/java/mydemo/models/HelloWorldResponse.java
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/application/src/main/resources/application.yml
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/application/src/main/resources/logback-spring.xml
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/application/src/main/resources/static/index.html
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/cleanup.sh
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/integration-tests/pom.xml
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/integration-tests/src/test/java/mydemo/HelloWorldControllerTest.java
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/integration-tests/src/test/resources/expected.json
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/pom.xml
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/settings.xml
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/unit-tests/pom.xml
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/unit-tests/src/test/java/mydemo/UnitTest.java
Labels: REVIEW

#1823 gCTS docu fixes
  cmd/gctsCloneRepository_generated.go
  cmd/gctsCreateRepository_generated.go
  cmd/gctsDeploy_generated.go
  cmd/gctsExecuteABAPUnitTests_generated.go
  documentation/docs/steps/gctsCloneRepository.md
  documentation/docs/steps/gctsCreateRepository.md
  documentation/docs/steps/gctsDeploy.md
  documentation/docs/steps/gctsExecuteABAPUnitTests.md
  resources/metadata/gctsCloneRepository.yaml
  resources/metadata/gctsCreateRepository.yaml
  resources/metadata/gctsDeployCommit.yaml
  resources/metadata/gctsExecuteABAPUnitTests.yaml
Labels: Git-CTS, REVIEW, documentation

#1782 Fetch config parameters from vault
  integration/integration_vault_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/mocks/vaultClient.go
  pkg/config/stepmeta.go
  pkg/config/vault.go
  pkg/config/vault_test.go
  pkg/vault/vault.go
Labels: Vault

#1824 chore(actions): cache Golang packages
  .github/workflows/verify-go.yml
Labels: REVIEW

#1148 chore(pipeline): add Code Climate coverage reporting for GO
  .github/workflows/verify-go.yml
Labels: REVIEW

#1757 [WIP] Add abap utils pkg - ABAP Environment Steps
  cmd/abapEnvironmentPullGitRepo.go
  cmd/abapEnvironmentPullGitRepo_test.go
  cmd/abapEnvironmentRunATCCheck.go
  cmd/abapEnvironmentRunATCCheck_test.go
  pkg/abaputils/abaputils.go
  pkg/abaputils/abaputils_test.go
  pkg/cloudfoundry/CloudFoundry_test.go
  pkg/cloudfoundry/Services.go
Labels: ABAP, work in progress 🚧

#1526 Introducing new step 'gctsRollback'
  cmd/gctsDeploy.go
  cmd/gctsDeploy_test.go
  cmd/gctsRollback.go
  cmd/gctsRollback_generated.go
  cmd/gctsRollback_generated_test.go
  cmd/gctsRollback_test.go
  cmd/piper.go
  documentation/docs/steps/gctsRollback.md
  documentation/mkdocs.yml
  resources/metadata/gctsRollback.yaml
  test/groovy/CommonStepsTest.groovy
  vars/gctsRollback.groovy
Labels: Git-CTS

#1837 Bugfix: Convert int/float parameters
  cmd/piper.go
  cmd/piper_test.go
Labels: REVIEW, bug :bug:, go-piper

#1847 fix(sonar): correct type for custom TLS certificates
  cmd/sonarExecuteScan.go
  cmd/sonarExecuteScan_generated.go
  cmd/sonarExecuteScan_test.go
  resources/metadata/sonar.yaml
Labels: REVIEW

#1775 detectExecuteScan : Changes to include user group and handle build fails
  cmd/detectExecuteScan.go
  cmd/detectExecuteScan_generated.go
  cmd/detectExecuteScan_test.go
  resources/metadata/detect.yaml
Labels: REVIEW

#1850 Support m2path for mtaBuild
  cmd/kanikoExecute_test.go
  cmd/mtaBuild.go
  cmd/mtaBuild_test.go
  cmd/xsDeploy_test.go
  pkg/command/command.go
  pkg/maven/settings_test.go
  pkg/mock/fileUtils.go
  pkg/mock/runner.go
  pkg/piperutils/FileUtils.go
Labels: REVIEW

#1851 Bugfix: Convert int/float parameters (2nd try)
  cmd/piper.go
  cmd/piper_test.go
Labels: REVIEW, bug :bug:, config, go-piper

#1856 Add mta alias for maven parameter
  cmd/mtaBuild_generated.go
  resources/metadata/mtaBuild.yaml
Labels: REVIEW

#1829 New step mavenExecuteIntegration
  cmd/mavenExecuteIntegration.go
  cmd/mavenExecuteIntegration_generated.go
  cmd/mavenExecuteIntegration_generated_test.go
  cmd/mavenExecuteIntegration_test.go
  cmd/piper.go
  documentation/docs/steps/mavenExecuteIntegration.md
  integration/integration_maven_test.go
  integration/testdata/TestMavenIntegration/cloud-sdk-spring-archetype/.pipeline/config.yml
  integration/testdata/TestMavenIntegration/cloud-sdk-tomee-archetype/.pipeline/config.yml
  resources/metadata/mavenExecuteIntegration.yaml
  src/com/sap/piper/DownloadCacheUtils.groovy
  test/groovy/CommonStepsTest.groovy
  test/groovy/MavenExecuteIntegrationTest.groovy
  vars/dockerExecute.groovy
  vars/mavenExecuteIntegration.groovy
  vars/piperExecuteBin.groovy
  vars/piperStageWrapper.groovy
Labels: REVIEW, go-piper

#1866 Declare non-optional server URLs mandatory
  cmd/detectExecuteScan_generated.go
  cmd/fortifyExecuteScan_generated.go
  resources/metadata/detect.yaml
  resources/metadata/fortify.yaml
Labels: REVIEW, go-piper

#1855 Support maven params in detect scan
  cmd/detectExecuteScan.go
  cmd/detectExecuteScan_generated.go
  cmd/detectExecuteScan_test.go
  cmd/kanikoExecute_test.go
  cmd/mtaBuild.go
  cmd/mtaBuild_test.go
  cmd/xsDeploy_test.go
  pkg/maven/maven.go
  pkg/maven/maven_test.go
  pkg/maven/settings.go
  pkg/maven/settings_test.go
  pkg/mock/fileUtils.go
  pkg/piperutils/FileUtils.go
  resources/metadata/detect.yaml
  vars/detectExecuteScan.groovy
Labels: REVIEW

#1869 mavenExecuteIntegration: Remove test collection
  test/groovy/MavenExecuteIntegrationTest.groovy
  vars/mavenExecuteIntegration.groovy
Labels: REVIEW

#1840 Improve testability of abap steps
  cmd/abapEnvironmentPullGitRepo.go
  cmd/abapEnvironmentPullGitRepo_test.go
  cmd/abapEnvironmentRunATCCheck.go
  cmd/abapEnvironmentRunATCCheck_test.go
  pkg/abaputils/abaputils.go
  pkg/abaputils/abaputils_test.go
Labels: ABAP, REVIEW
