Repository SAP/jenkins-library, pull requests merged in 2020-05, with the labels that each got.

#1500 fix(protecode): correct provided user parameter
  vars/protecodeExecuteScan.groovy
Labels: REVIEW

#1501 test: enable common test cases for go steps
  test/groovy/CommonStepsTest.groovy
  vars/piperExecuteBin.groovy
Labels: REVIEW

#1495 fix: prevent script to json conversion
  test/groovy/AbapEnvironmentPullGitRepoTest.groovy
  test/groovy/GithubPublishReleaseTest.groovy
  vars/abapEnvironmentPullGitRepo.groovy
  vars/cloudFoundryCreateServiceKey.groovy
  vars/cloudFoundryDeleteService.groovy
  vars/gctsCreateRepository.groovy
  vars/githubPublishRelease.groovy
  vars/piperExecuteBin.groovy
  vars/protecodeExecuteScan.groovy
Labels: REVIEW

#1508 fix(protecode): handle api request issues
  pkg/protecode/protecode.go
Labels: REVIEW

#1507 docs: fix protecode example
  documentation/docs/steps/protecodeExecuteScan.md
Labels: REVIEW

#1442 Disable duplicate go integration tests
  .github/workflows/verify-go.yml
Labels: REVIEW

#1432 Allow configuration of log format, change default to fixed-width
  cmd/piper.go
  pkg/log/log.go
  resources/default_pipeline_environment.yml
Labels: REVIEW

#1499 Let users configure the sap npm registry for mta builds via config.yml
  vars/mtaBuild.groovy
Labels: REVIEW

#1502 refactor(protecode): handle DOCKER_CONFIG in go
  cmd/protecodeExecuteScan.go
  vars/protecodeExecuteScan.groovy
Labels: REVIEW

#1493 Fix maven parameter handling
  cmd/mavenExecute.go
  cmd/mavenExecute_test.go
  cmd/piper.go
  cmd/piper_test.go
  documentation/docs/steps/mavenExecute.md
  pkg/maven/maven.go
  pkg/maven/maven_test.go
  src/com/sap/piper/BashUtils.groovy
  src/com/sap/piper/Utils.groovy
  src/com/sap/piper/versioning/MavenArtifactVersioning.groovy
  test/groovy/ArtifactSetVersionTest.groovy
  test/groovy/com/sap/piper/versioning/MavenArtifactVersioningTest.groovy
  vars/mavenBuild.groovy
  vars/mavenExecute.groovy
  vars/piperExecuteBin.groovy
Labels: REVIEW

#1516 Mass enable abapEnvironmentPullGitRepo
  cmd/abapEnvironmentPullGitRepo.go
  cmd/abapEnvironmentPullGitRepo_generated.go
  cmd/abapEnvironmentPullGitRepo_test.go
  documentation/docs/steps/abapEnvironmentPullGitRepo.md
  resources/metadata/abapEnvironmentPullGitRepo.yaml
Labels: REVIEW

#1524 fix(sonar): handle piper-bin error result
  vars/sonarExecuteScan.groovy
Labels: REVIEW

#1521 Enable use of customDefaults from Project Config also in Groovy
  DEVELOPMENT.md
  documentation/docs/configuration.md
  documentation/docs/pipelines/cloud-sdk/shared-config-between-projects.md
  documentation/mkdocs.yml
  src/com/sap/piper/DefaultValueCache.groovy
  src/com/sap/piper/Utils.groovy
  test/groovy/PrepareDefaultValuesTest.groovy
  test/groovy/SetupCommonPipelineEnvironmentTest.groovy
  vars/prepareDefaultValues.groovy
  vars/setupCommonPipelineEnvironment.groovy
Labels: REVIEW

#1529 Reading defaults: Make sure all io.ReadClosers are closed
  pkg/config/defaults.go
Labels: REVIEW, bug :bug:, go-piper

#1454 Add abapEnvironmentRunATCCheck step
  cmd/abapEnvironmentRunATCCheck.go
  cmd/abapEnvironmentRunATCCheck_generated.go
  cmd/abapEnvironmentRunATCCheck_generated_test.go
  cmd/abapEnvironmentRunATCCheck_test.go
  cmd/cloudFoundryCreateServiceKey.go
  cmd/piper.go
  documentation/docs/steps/abapEnvironmentRunATCCheck.md
  pkg/cloudfoundry/Authentication.go
  pkg/cloudfoundry/CloudFoundry_test.go
  pkg/cloudfoundry/Services.go
  resources/metadata/abapEnvironmentRunATCCheck.yaml
  test/groovy/CommonStepsTest.groovy
  vars/abapEnvironmentRunATCCheck.groovy
  vars/cloudFoundryCreateServiceKey.groovy
Labels: ABAP, REVIEW

#1539 add -f option to kanikoExecute containerPreparationCommand remove
  resources/default_pipeline_environment.yml
  test/groovy/KanikoExecuteTest.groovy
Labels: REVIEW

#1538 Optionally ignore custom defaults
  cmd/getConfig.go
  cmd/piper.go
  pkg/config/config.go
  pkg/config/config_test.go
  src/com/sap/piper/DefaultValueCache.groovy
  test/groovy/SetupCommonPipelineEnvironmentTest.groovy
  vars/piperExecuteBin.groovy
  vars/setupCommonPipelineEnvironment.groovy
Labels: REVIEW, go-piper

#1534 feat(sonar): write flag for sonar execution to influx
  cmd/sonarExecuteScan.go
  cmd/sonarExecuteScan_generated.go
  resources/metadata/sonar.yaml
  src/com/sap/piper/analytics/InfluxData.groovy
  test/groovy/com/sap/piper/analytics/InfluxDataTest.groovy
  vars/sonarExecuteScan.groovy
Labels: REVIEW

#1549 fix(versioning): commit only modified files
  cmd/artifactPrepareVersion.go
  cmd/artifactPrepareVersion_test.go
Labels: REVIEW

#1543 fix(spinnaker): fix MissingPropertyException
  test/groovy/SpinnakerTriggerPipelineTest.groovy
  vars/spinnakerTriggerPipeline.groovy
Labels: REVIEW

#1554 Create step to save container image
  cmd/containerSaveImage.go
  cmd/containerSaveImage_generated.go
  cmd/containerSaveImage_generated_test.go
  cmd/containerSaveImage_test.go
  cmd/piper.go
  resources/metadata/savecontainer.yaml
Labels: go-piper

#1561 Fix: Execute ABAP run ATC check test in temp folder
  cmd/abapEnvironmentRunATCCheck_test.go
Labels: REVIEW

#1558 Ignore invalid entries in custom defaults
  test/groovy/SetupCommonPipelineEnvironmentTest.groovy
  test/groovy/com/sap/piper/UtilsTest.groovy
  vars/setupCommonPipelineEnvironment.groovy
Labels: REVIEW

#1513 Improve approval logging
  test/groovy/templates/PiperPipelineStageConfirmTest.groovy
  vars/piperPipelineStageConfirm.groovy
Labels: REVIEW

#1476 Introducing new step 'gctsDeployCommit'
  cmd/gctsDeploy.go
  cmd/gctsDeploy_generated.go
  cmd/gctsDeploy_generated_test.go
  cmd/gctsDeploy_test.go
  cmd/piper.go
  documentation/docs/steps/gctsDeployCommit.md
  resources/metadata/gctsDeployCommit.yaml
  test/groovy/CommonStepsTest.groovy
  vars/gctsDeploy.groovy
Labels: ABAP, REVIEW

#1478 Piper steps: Issue SUCCESS message
  cmd/abapEnvironmentPullGitRepo_generated.go
  cmd/abapEnvironmentRunATCCheck_generated.go
  cmd/artifactPrepareVersion.go
  cmd/artifactPrepareVersion_generated.go
  cmd/checkmarxExecuteScan_generated.go
  cmd/cloudFoundryCreateServiceKey_generated.go
  cmd/cloudFoundryDeleteService_generated.go
  cmd/containerSaveImage_generated.go
  cmd/detectExecuteScan_generated.go
  cmd/gctsCreateRepository_generated.go
  cmd/gctsDeploy_generated.go
  cmd/githubCreatePullRequest_generated.go
  cmd/githubPublishRelease_generated.go
  cmd/karmaExecuteTests_generated.go
  cmd/kubernetesDeploy_generated.go
  cmd/malwareExecuteScan_generated.go
  cmd/mavenBuild_generated.go
  cmd/mavenExecuteStaticCodeChecks_generated.go
  cmd/mavenExecute_generated.go
  cmd/mtaBuild_generated.go
  cmd/nexusUpload_generated.go
  cmd/npmExecuteScripts_generated.go
  cmd/protecodeExecuteScan_generated.go
  cmd/sonarExecuteScan_generated.go
  cmd/version_generated.go
  cmd/xsDeploy_generated.go
  pkg/generator/helper/helper.go
  pkg/generator/helper/testdata/TestProcessMetaFiles/custom_step_code_generated.golden
  pkg/generator/helper/testdata/TestProcessMetaFiles/step_code_generated.golden
Labels: go-piper

#1536 Use mtaBuild step from go
  cmd/mtaBuild_generated.go
  resources/metadata/mtaBuild.yaml
  test/groovy/CommonStepsTest.groovy
  test/groovy/FioriOnCloudPlatformPipelineTest.groovy
  test/groovy/MtaBuildTest.groovy
  vars/mtaBuild.groovy
Labels: REVIEW

#1570 Fix mtarName config param handling
  cmd/mtaBuild.go
  cmd/mtaBuild_test.go
Labels: REVIEW, bug :bug:, go-piper

#1562 Fix container condition handling
  cmd/getConfig.go
  cmd/getConfig_test.go
  pkg/config/stepmeta.go
  pkg/config/stepmeta_test.go
Labels: go-piper

#1428 Fortify implementation in golang
  .gitignore
  cmd/artifactPrepareVersion_generated.go
  cmd/artifactPrepareVersion_test.go
  cmd/checkmarxExecuteScan_generated.go
  cmd/detectExecuteScan_generated.go
  cmd/fortifyExecuteScan.go
  cmd/fortifyExecuteScan_generated.go
  cmd/fortifyExecuteScan_generated_test.go
  cmd/fortifyExecuteScan_test.go
  cmd/gctsCreateRepository_generated.go
  cmd/githubCreatePullRequest_generated.go
  cmd/githubPublishRelease_generated.go
  cmd/karmaExecuteTests_generated.go
  cmd/kubernetesDeploy_generated.go
  cmd/mavenBuild_generated.go
  cmd/mtaBuild_generated.go
  cmd/nexusUpload_generated.go
  cmd/npmExecuteScripts_generated.go
  cmd/piper.go
  cmd/protecodeExecuteScan_generated.go
  cmd/sonarExecuteScan_generated.go
  cmd/xsDeploy_generated.go
  documentation/docs/steps/fortifyExecuteScan.md
  go.mod
  go.sum
  pkg/checkmarx/checkmarx_test.go
  pkg/fortify/fortify.go
  pkg/fortify/fortify_test.go
  pkg/generator/helper/helper.go
  pkg/generator/helper/helper_test.go
  pkg/generator/helper/testdata/TestProcessMetaFiles/custom_step_code_generated.golden
  pkg/generator/helper/testdata/TestProcessMetaFiles/step_code_generated.golden
  pkg/http/http.go
  pkg/piperutils/slices.go
  pkg/piperutils/templateUtils.go
  pkg/piperutils/templateUtils_test.go
  pkg/piperutils/testdata/2_setup.py
  pkg/piperutils/testdata/VERSION.TXT
  pkg/piperutils/testdata/setup.py
  pkg/piperutils/testdata/test2_pom.xml
  pkg/piperutils/testdata/test_pom.xml
  pkg/versioning/descriptorUtils.go
  pkg/versioning/descriptorUtils_test.go
  pkg/versioning/docker.go
  pkg/versioning/inifile.go
  pkg/versioning/jsonfile.go
  pkg/versioning/maven.go
  pkg/versioning/pip.go
  pkg/versioning/pip_test.go
  pkg/versioning/versionfile.go
  pkg/versioning/versioning.go
  pkg/versioning/versioning_test.go
  pkg/versioning/yamlfile.go
  resources/metadata/fortify.yaml
  test/groovy/CommonStepsTest.groovy
  vars/fortifyExecuteScan.groovy
Labels: go-piper, work in progress 🚧

#1584 piperExecuteBin - prevent non-speaking exit code 1 error
  cmd/getConfig.go
  cmd/getConfig_test.go
  test/groovy/PiperExecuteBinTest.groovy
  vars/piperExecuteBin.groovy
Labels: go-piper

#1592 Allow custom options for src, exclude in fortify translate
  cmd/fortifyExecuteScan.go
  cmd/fortifyExecuteScan_generated.go
  cmd/fortifyExecuteScan_test.go
  resources/metadata/fortify.yaml
Labels: REVIEW, enhancement, go-piper

#1580 Remove curl for unstashing binary
  src/com/sap/piper/JenkinsUtils.groovy
  src/com/sap/piper/PiperGoUtils.groovy
  test/groovy/com/sap/piper/PiperGoUtilsTest.groovy
  test/groovy/util/JenkinsHttpRequestRule.groovy
Labels: REVIEW

#1605 Fix injection of download cache parameters
  src/com/sap/piper/BuildTool.groovy
  src/com/sap/piper/DownloadCacheUtils.groovy
  test/groovy/DownloadCacheUtilsTest.groovy
  vars/artifactPrepareVersion.groovy
  vars/fortifyExecuteScan.groovy
  vars/mavenBuild.groovy
  vars/mavenExecute.groovy
  vars/mavenExecuteStaticCodeChecks.groovy
  vars/mtaBuild.groovy
  vars/nexusUpload.groovy
  vars/npmExecuteScripts.groovy
Labels: REVIEW, bug :bug:, go-piper

#1612 reload default value cache also in case we have customDefaultsFromFil…
  src/com/sap/piper/DefaultValueCache.groovy
Labels: bug :bug:

#1611 Strip "./" from paths to artifacts
  src/com/sap/piper/JenkinsUtils.groovy
Labels: REVIEW
