Repository SAP/jenkins-library, pull requests merged in 2020-10, with the labels that each got.

#2105 Update Cloud SDK stash settings and stage defaults
  resources/com.sap.piper/pipeline/cloudSdkContainersMap.yml
  resources/com.sap.piper/pipeline/cloudSdkJavaStashSettings.yml
  resources/com.sap.piper/pipeline/cloudSdkJavascriptStashSettings.yml
  resources/com.sap.piper/pipeline/cloudSdkMtaStashSettings.yml
  resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
Labels: REVIEW, sap-cloud-sdk

#2110 chore(git): add binary file to ignore list
  .gitignore
Labels: REVIEW

#2051 Provide Additional pod properties for dockerExecuteOnKubernetes
  test/groovy/DockerExecuteOnKubernetesTest.groovy
  vars/dockerExecute.groovy
  vars/dockerExecuteOnKubernetes.groovy
Labels: REVIEW

#2111 chore(sonar): assign error categories to know error cases
  cmd/sonarExecuteScan.go
Labels: REVIEW

#2114 Fix Cloud SDK Pipeline stash settings for security stage
  resources/com.sap.piper/pipeline/cloudSdkJavaStashSettings.yml
  resources/com.sap.piper/pipeline/cloudSdkJavascriptStashSettings.yml
  resources/com.sap.piper/pipeline/cloudSdkMtaStashSettings.yml
Labels: REVIEW, sap-cloud-sdk

#2115 Update Go dependencies
  go.mod
  go.sum
Labels: REVIEW, go-piper

#2083 Move setting git info in cpe from stage init to setupCPE step
  test/groovy/SetupCommonPipelineEnvironmentTest.groovy
  test/groovy/templates/PiperPipelineStageInitTest.groovy
  vars/piperPipelineStageInit.groovy
  vars/setupCommonPipelineEnvironment.groovy
Labels: REVIEW

#2102 fix(cfDeploy): mark dockerUsername as secret
  cmd/cloudFoundryDeploy_generated.go
  resources/metadata/cloudFoundryDeploy.yaml
Labels: REVIEW

#2096 Adapt pipeline documentation
  documentation/docs/pipelines/abapEnvironment/configuration.md
Labels: REVIEW

#2125 chore(detect): add error category for policy violations
  cmd/detectExecuteScan.go
Labels: REVIEW

#2127 chore(sonar): add error category
  cmd/sonarExecuteScan.go
Labels: REVIEW

#2130 chore(detect): add error category for config issues
  cmd/detectExecuteScan.go
Labels: REVIEW

#2144 WhiteSource: Pass correct module path to npm.InstallAllDependencies()
  cmd/whitesourceExecuteScan.go
  cmd/whitesourceExecuteScan_test.go
Labels: bug :bug:, go-piper

#2146 fix(influx): read simple values from json
  src/com/sap/piper/analytics/InfluxData.groovy
Labels: REVIEW

#2032 Feature/fetch secrets from vault
  DEVELOPMENT.md
  cmd/artifactPrepareVersion_generated.go
  cmd/checkmarxExecuteScan_generated.go
  cmd/cloudFoundryCreateServiceKey_generated.go
  cmd/cloudFoundryCreateService_generated.go
  cmd/cloudFoundryDeleteService_generated.go
  cmd/cloudFoundryDeploy_generated.go
  cmd/detectExecuteScan_generated.go
  cmd/fortifyExecuteScan_generated.go
  cmd/piper.go
  cmd/sonarExecuteScan_generated.go
  documentation/developer_hints/VaultResourceReference.md
  pkg/config/config.go
  pkg/config/interpolation/interpolation.go
  pkg/config/interpolation/interpolation_test.go
  pkg/config/stepmeta.go
  pkg/config/stepmeta_test.go
  pkg/config/vault.go
  pkg/config/vault_test.go
  pkg/vault/client.go
  pkg/vault/client_test.go
  resources/metadata/checkmarx.yaml
  resources/metadata/cloudFoundryCreateService.yaml
  resources/metadata/cloudFoundryCreateServiceKey.yaml
  resources/metadata/cloudFoundryDeleteService.yaml
  resources/metadata/cloudFoundryDeploy.yaml
  resources/metadata/detect.yaml
  resources/metadata/fortify.yaml
  resources/metadata/sonar.yaml
  resources/metadata/versioning.yaml
  vars/cloudFoundryDeploy.groovy
  vars/piperExecuteBin.groovy
Labels: REVIEW

#2166 feat(sonar): use SonarSource sonar-scanner-cli Docker image
  cmd/sonarExecuteScan_generated.go
  resources/metadata/sonar.yaml
Labels: REVIEW, Sonar

#2176 WhiteSource: Remove performance-tests from default maven excludes
  cmd/whitesourceExecuteScan.go
  cmd/whitesourceExecuteScan_generated.go
  cmd/whitesourceExecuteScan_test.go
  resources/metadata/whitesource.yaml
Labels: bug :bug:, go-piper

#2177 fix(docs): correct md syntax for headlines
  pkg/documentation/generator/description.go
  pkg/documentation/generator/description_test.go
  pkg/documentation/generator/helper.go
  pkg/documentation/generator/parameters.go
Labels: REVIEW, documentation

#2182 ABAP steps docu improvements
  cmd/abapEnvironmentCheckoutBranch_generated.go
  cmd/abapEnvironmentCloneGitRepo_generated.go
  cmd/abapEnvironmentPullGitRepo_generated.go
  cmd/abapEnvironmentRunATCCheck_generated.go
  documentation/docs/pipelines/abapEnvironment/introduction.md
  resources/metadata/abapEnvironmentCheckoutBranch.yaml
  resources/metadata/abapEnvironmentCloneGitRepo.yaml
  resources/metadata/abapEnvironmentPullGitRepo.yaml
  resources/metadata/abapEnvironmentRunATCCheck.yaml
Labels: REVIEW

#2187 Docu description of buildTool
  vars/cloudFoundryDeploy.groovy
Labels: documentation

#2188 ABAP Pipeline docu fixes
  documentation/docs/pipelines/abapEnvironment/introduction.md
Labels: REVIEW, documentation

#2193 fix(docs): flag mandatory parameters with default value as non-mandatory
  pkg/documentation/generator/main.go
  pkg/documentation/generator/main_test.go
  pkg/documentation/generator/parameters.go
Labels: REVIEW, documentation

#2192 fix(cfDeploy): correct type of default value
  resources/metadata/cloudFoundryDeploy.yaml
Labels: REVIEW, documentation

#2196 Also stash war files as build result
  resources/default_pipeline_environment.yml
Labels: REVIEW

#2022 docs: use custom defaults during docs generation
  .github/workflows/documentation.yaml
  pkg/documentation/generator.go
  pkg/documentation/generator/main.go
  pkg/documentation/generator/main_test.go
  pkg/documentation/generator/metadata.go
  pkg/documentation/generator/metadata_test.go
Labels: REVIEW, documentation

#2195 fix(influx): correct project_name field name
  cmd/checkmarxExecuteScan.go
  cmd/checkmarxExecuteScan_generated.go
  resources/metadata/checkmarx.yaml
Labels: Influx, REVIEW

#2204 Add initial docu for scenario: "Build and Publish ABAP Add-ons"
  documentation/docs/scenarios/abapEnvironmentAddons.md
  documentation/mkdocs.yml
Labels: REVIEW, documentation

#2178 feat(Gitops): new step to update deployment
  cmd/gitopsUpdateDeployment.go
  cmd/gitopsUpdateDeployment_generated.go
  cmd/gitopsUpdateDeployment_generated_test.go
  cmd/gitopsUpdateDeployment_test.go
  cmd/piper.go
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/piperutils/FileUtils.go
  resources/metadata/gitopsUpdateDeployment.yaml
  test/groovy/CommonStepsTest.groovy
  vars/gitopsUpdateDeployment.groovy
Labels: REVIEW

#2207 whitesourceExecuteScan: Re-organize code between step and whitesource package
  cmd/whitesourceExecuteScan.go
  cmd/whitesourceExecuteScan_test.go
  pkg/whitesource/scan.go
  pkg/whitesource/scanMTA.go
  pkg/whitesource/scanMTA_test.go
  pkg/whitesource/scanMaven.go
  pkg/whitesource/scanMaven_test.go
  pkg/whitesource/scanNPM.go
  pkg/whitesource/scanNPM_test.go
  pkg/whitesource/scanOptions.go
  pkg/whitesource/scanReports.go
  pkg/whitesource/scanReports_test.go
  pkg/whitesource/scanUA.go
  pkg/whitesource/scanUA_test.go
  pkg/whitesource/scan_test.go
  pkg/whitesource/sytemMock.go
  pkg/whitesource/utils.go
  pkg/whitesource/utilsMock.go
Labels: Code Quality, REVIEW, go-piper

#2205 Update abapEnvironmentAddons.md
  documentation/docs/scenarios/abapEnvironmentAddons.md
Labels: REVIEW, documentation

#2212 Cloud SDK: Update stash settings, stage defaults and containers map for a single call of integration stage
  documentation/docs/pipelines/cloud-sdk/configuration.md
  resources/com.sap.piper/pipeline/cloudSdkContainersMap.yml
  resources/com.sap.piper/pipeline/cloudSdkJavaStashSettings.yml
  resources/com.sap.piper/pipeline/cloudSdkJavascriptStashSettings.yml
  resources/com.sap.piper/pipeline/cloudSdkMtaStashSettings.yml
  resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
Labels: REVIEW, sap-cloud-sdk

#2219 fix(influx): adjust influx field types for fortify
  cmd/fortifyExecuteScan.go
  cmd/fortifyExecuteScan_generated.go
  cmd/fortifyExecuteScan_test.go
  go.sum
  resources/metadata/fortify.yaml
Labels: Fortify, Influx, REVIEW

#2236 Fix cloudFoundryDeploy documentation
  vars/cloudFoundryDeploy.groovy
Labels: REVIEW

#2238 detectExecuteScan: Clean up detect.sh
  cmd/detectExecuteScan.go
  cmd/detectExecuteScan_test.go
  cmd/mtaBuild_test.go
  pkg/maven/maven.go
  pkg/maven/settings.go
Labels: Code Quality, bug :bug:

#2253 Remove "onlyInProductiveBranch" check
  resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
  test/groovy/templates/PiperInitRunStageConfigurationTest.groovy
  vars/piperInitRunStageConfiguration.groovy
Labels: REVIEW

#2246 whitesourceExecuteScan-go: Implement parameters "timeout", "createProductFromPipeline"
  cmd/whitesourceExecuteScan.go
  cmd/whitesourceExecuteScan_generated.go
  cmd/whitesourceExecuteScan_test.go
  pkg/whitesource/sytemMock.go
  pkg/whitesource/whitesource.go
  pkg/whitesource/whitesource_test.go
  resources/metadata/whitesource.yaml
Labels: REVIEW, documentation, enhancement, go-piper

#1913 Up for discussion: Embed best practices (?) in generated steps
  pkg/generator/helper/helper.go
Labels: Code Quality, discussion, go-piper

#2279 Pass settings file also to install-file
  cmd/mavenExecuteIntegration.go
  cmd/mavenExecuteStaticCodeChecks.go
  cmd/mtaBuild.go
  pkg/maven/maven.go
  pkg/maven/maven_test.go
Labels: REVIEW

#2280 Install artifacts before whitesource scan
  cmd/whitesourceExecuteScan.go
  cmd/whitesourceExecuteScan_generated.go
  pkg/whitesource/scanMaven.go
  pkg/whitesource/scanOptions.go
  resources/metadata/whitesource.yaml
Labels: REVIEW
