Repository SAP/jenkins-library, pull requests merged in 2021-02, with the labels that each got.

#2501 feat(whitesourceExecuteScan): UA for all build tools, e.g. maven & npm
  cmd/whitesourceExecuteScan.go
  cmd/whitesourceExecuteScan_generated.go
  pkg/mock/fileUtils.go
  pkg/versioning/docker.go
  pkg/versioning/docker_test.go
  pkg/versioning/pip.go
  pkg/versioning/pip_test.go
  pkg/versioning/versioning.go
  pkg/versioning/versioning_test.go
  pkg/whitesource/configHelper.go
  pkg/whitesource/configHelper_test.go
  pkg/whitesource/scan.go
  pkg/whitesource/scanMTA_test.go
  pkg/whitesource/scanMaven_test.go
  pkg/whitesource/scanNPM_test.go
  pkg/whitesource/scanOptions.go
  pkg/whitesource/scanUA.go
  pkg/whitesource/scanUA_test.go
  pkg/whitesource/utils.go
  pkg/whitesource/utilsMock.go
  resources/default_pipeline_environment.yml
  resources/metadata/whitesource.yaml
  src/com/sap/piper/WhitesourceConfigurationHelper.groovy
  src/com/sap/piper/integration/WhitesourceOrgAdminRepository.groovy
  src/com/sap/piper/integration/WhitesourceRepository.groovy
  test/groovy/CommonStepsTest.groovy
  test/groovy/WhitesourceExecuteScanTest.groovy
  test/groovy/com/sap/piper/WhitesourceConfigurationHelperTest.groovy
  test/groovy/com/sap/piper/integration/WhitesourceOrgAdminRepositoryTest.groovy
  test/groovy/com/sap/piper/integration/WhitesourceRepositoryTest.groovy
  vars/whitesourceExecuteScan.groovy
Labels: WhiteSource

#2575 Force WS Project update for mvn plugin
  pkg/whitesource/scanMTA_test.go
  pkg/whitesource/scanMaven.go
  pkg/whitesource/scanMaven_test.go
Labels: WhiteSource, enhancement, go-piper

#2576 test: allow usage of httpmock in tests
  go.mod
  go.sum
  pkg/http/http.go
  pkg/http/http_test.go
Labels: REVIEW

#2544 feat(versioning): add re-use function for proper Scan versioning
  pkg/versioning/descriptorUtils.go
  pkg/versioning/descriptorUtils_test.go
Labels: versioning

#2580 chore(http): allow to send prepared requests
  pkg/http/http.go
  pkg/http/http_test.go
Labels: REVIEW

#2595 Add CNAME file to documentation
  documentation/docs/CNAME
Labels: REVIEW

#2439 (Vault) Improvements
  cmd/piper.go
  documentation/docs/images/jenkins-vault-token-credential.png
  documentation/docs/images/vault-secret-engine-enable.png
  documentation/docs/infrastructure/vault.md
  pkg/config/config.go
  pkg/config/interpolation/interpolation.go
  pkg/config/stepmeta.go
  pkg/config/stepmeta_test.go
  pkg/config/vault.go
  pkg/config/vault_test.go
  pkg/vault/client.go
  vars/piperExecuteBin.groovy
Labels: ON HOLD

#2613 Increase cf-cli version for abap steps
  cmd/abapEnvironmentAssembleConfirm_generated.go
  cmd/abapEnvironmentAssemblePackages_generated.go
  cmd/abapEnvironmentCheckoutBranch_generated.go
  cmd/abapEnvironmentCloneGitRepo_generated.go
  cmd/abapEnvironmentPullGitRepo_generated.go
  cmd/abapEnvironmentRunATCCheck_generated.go
  resources/metadata/abapEnvironmentAssembleConfirm.yaml
  resources/metadata/abapEnvironmentAssemblePackages.yaml
  resources/metadata/abapEnvironmentCheckoutBranch.yaml
  resources/metadata/abapEnvironmentCloneGitRepo.yaml
  resources/metadata/abapEnvironmentPullGitRepo.yaml
  resources/metadata/abapEnvironmentRunATCCheck.yaml
Labels: REVIEW

#2621 Updates for ABAP Environment release 2102
  documentation/docs/scenarios/abapEnvironmentAddons.md
  test/groovy/templates/AbapEnvironmentPipelineStageCloneRepositoriesTest.groovy
  vars/abapEnvironmentPipelineStageCloneRepositories.groovy
Labels: ABAP

#2646 tests: expose sonar test secret to workflows
  .github/workflows/integration-tests-pr.yaml
  .github/workflows/integration-tests.yaml
Labels: REVIEW

#2648 fix(sonar): prevents step from contacting sonar API for legacy systems
  cmd/sonarExecuteScan.go
Labels: REVIEW

#2650 fix(sonar): remove warnings handling
  pkg/sonar/taskService.go
Labels: REVIEW

#2649 fix(sonar): use token provided by sonar-scanner-jenkins plugin
  cmd/sonarExecuteScan.go
Labels: REVIEW

#2653 fix(sonar): disable measurements if no credentials are provided
  cmd/sonarExecuteScan.go
Labels: REVIEW
