Repository SAP/jenkins-library, pull requests merged in 2024-09, with the labels that each got.

#5040 fix(http): Use configured logger for retryClient
  pkg/http/http.go
Labels: bug :bug:

#5032 feat(trustengine): Integrate Trust Engine into step config resolver
  cmd/piper.go
  pkg/config/config.go
  pkg/config/trustengine.go
  pkg/config/trustengine_test.go
  pkg/trustengine/trustengine.go
  pkg/trustengine/trustengine_test.go
Labels: feature

#5039 addon.yml may now contain wildCard MAXX
  pkg/abap/aakaas/componentVersion.go
  pkg/abap/aakaas/productVersion.go
  pkg/abap/aakaas/versionables.go
  pkg/abap/aakaas/versionables_test.go
Labels: ABAP

#5038 feat(trustengine): Add new resource reference to parameter docs generation
  pkg/documentation/generator/parameters.go
Labels: ON HOLD, feature
