Repository SAP/jenkins-library, pull requests merged in 2025-03, with the labels that each got.

#5290 fix(docs): invalid anchor
  cmd/artifactPrepareVersion_generated.go
  cmd/kanikoExecute_generated.go
  resources/metadata/artifactPrepareVersion.yaml
  resources/metadata/kanikoExecute.yaml
Labels: Code Quality

#5291 fix(docs): invalid links
  documentation/docs/steps/isChangeInDevelopment.md
  documentation/docs/steps/uiVeri5ExecuteTests.md
Labels: Code Quality

#5293 fix: invalid anchors
  documentation/docs/steps/isChangeInDevelopment.md
Labels: Code Quality

#5292 fix: remove invalid secret references
  cmd/malwareExecuteScan_generated.go
  cmd/mtaBuild_generated.go
  resources/metadata/malwareExecuteScan.yaml
  resources/metadata/mtaBuild.yaml
Labels: Code Quality

#5296 ABAP Addon: Add details regarding SCR + API snapshot
  cmd/abapEnvironmentAssemblePackages_generated.go
  documentation/docs/scenarios/abapEnvironmentAddons.md
  documentation/docs/steps/abapEnvironmentAssemblePackages.md
  resources/metadata/abapEnvironmentAssemblePackages.yaml
Labels: documentation, ABAP

#5303 feat(telemetry): report binary version
  pkg/splunk/data.go
  pkg/splunk/splunk.go
Labels: telemetry
